"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DEFAULT_UNDERWRITING_SETTINGS, type UnderwritingSettings } from "@/features/flip-finder/underwriting";

type Assumption = { id: string; city: string; district: string | null; building_type: string | null; area_min: number | null; area_max: number | null; rooms: number | null; resale_price_per_m2_low: number; resale_price_per_m2_base: number; resale_price_per_m2_high: number; confidence: number };

export function InvestmentOsSettings() {
  const [settings, setSettings] = useState(DEFAULT_UNDERWRITING_SETTINGS);
  const [assumptions, setAssumptions] = useState<Assumption[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [market, setMarket] = useState({ city: "Łódź", district: "", buildingType: "", areaMin: "", areaMax: "", rooms: "", low: "", base: "", high: "", confidence: "70" });
  useEffect(() => {
    void Promise.all([fetch("/api/flip-finder/investment/settings").then((response) => response.json()), fetch("/api/flip-finder/investment/market-assumptions").then((response) => response.json())])
      .then(([settingsBody, assumptionsBody]) => { if (settingsBody.settings) setSettings(settingsBody.settings); if (Array.isArray(assumptionsBody.assumptions)) setAssumptions(assumptionsBody.assumptions); })
      .catch(() => setMessage("Nie udało się pobrać ustawień Investment OS."));
  }, []);
  const update = (key: keyof UnderwritingSettings, raw: string) => { const value = Number(raw); if (Number.isFinite(value) && value >= 0) setSettings((current) => ({ ...current, [key]: value })); };
  const updateRenovation = (key: keyof UnderwritingSettings["renovationPerM2"], raw: string) => { const value = Number(raw); if (Number.isFinite(value) && value >= 0) setSettings((current) => ({ ...current, renovationPerM2: { ...current.renovationPerM2, [key]: value } })); };
  const saveSettings = async () => { const response = await fetch("/api/flip-finder/investment/settings", mutation("PUT", settings)); setMessage(response.ok ? "Ustawienia zapisane. UNDERWRITER i CEO oznaczono jako STALE." : "Nie udało się zapisać ustawień."); };
  const saveMarket = async () => {
    const response = await fetch("/api/flip-finder/investment/market-assumptions", mutation("POST", { ...market, areaMin: optionalNumber(market.areaMin), areaMax: optionalNumber(market.areaMax), rooms: optionalNumber(market.rooms), low: Number(market.low), base: Number(market.base), high: Number(market.high), confidence: Number(market.confidence) }));
    const body = await response.json();
    if (response.ok && body.assumption) { setAssumptions((current) => [body.assumption, ...current]); setMessage("Założenie rynku zapisane. Dotknięte deale oznaczono jako STALE."); }
    else setMessage("Sprawdź zakres LOW ≤ BASE ≤ HIGH i confidence 0–100.");
  };
  return <div className="space-y-6">
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Koszt remontu i finansowanie</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Setting label="LIGHT zł/m²" value={settings.renovationPerM2.LIGHT} onChange={(value) => updateRenovation("LIGHT", value)} /><Setting label="STANDARD zł/m²" value={settings.renovationPerM2.STANDARD} onChange={(value) => updateRenovation("STANDARD", value)} /><Setting label="FULL zł/m²" value={settings.renovationPerM2.FULL} onChange={(value) => updateRenovation("FULL", value)} /><Setting label="Oprocentowanie roczne %" value={settings.financingAnnualRatePercent} onChange={(value) => update("financingAnnualRatePercent", value)} /><Setting label="Finansowany udział %" value={settings.financingLoanPercent} onChange={(value) => update("financingLoanPercent", value)} /><label className="flex items-center gap-2 rounded-lg border px-3"><input checked={settings.financingEnabled} onChange={(event) => setSettings((current) => ({ ...current, financingEnabled: event.target.checked }))} type="checkbox" />Uwzględnij finansowanie</label></div></section>
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Flip Investment OS · Underwriting</h2><p className="mt-1 text-sm text-muted-foreground">Centralne, trwałe założenia. Wyniki finansowe są liczone na serwerze, nie przyjmowane od klienta.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Setting label="Rezerwa %" value={settings.contingencyPercent} onChange={(value) => update("contingencyPercent", value)} /><Setting label="Koszt zakupu %" value={settings.purchaseTaxPercent} onChange={(value) => update("purchaseTaxPercent", value)} /><Setting label="Koszty stałe zakupu" value={settings.fixedPurchaseCosts} onChange={(value) => update("fixedPurchaseCosts", value)} /><Setting label="Koszt sprzedaży %" value={settings.salesCostPercent} onChange={(value) => update("salesCostPercent", value)} /><Setting label="Miesiące utrzymania" value={settings.holdingMonths} onChange={(value) => update("holdingMonths", value)} /><Setting label="Utrzymanie / miesiąc" value={settings.monthlyHoldingCost} onChange={(value) => update("monthlyHoldingCost", value)} /><Setting label="Minimalny zysk" value={settings.minimumProfitPLN} onChange={(value) => update("minimumProfitPLN", value)} /><Setting label="Minimalna marża %" value={settings.minimumMarginPercent} onChange={(value) => update("minimumMarginPercent", value)} /><Setting label="Minimalne ROI %" value={settings.minimumROI} onChange={(value) => update("minimumROI", value)} /><Setting label="Bufor negocjacyjny %" value={settings.targetNegotiationBufferPercent} onChange={(value) => update("targetNegotiationBufferPercent", value)} /></div><Button className="mt-4" onClick={() => void saveSettings()} type="button">Zapisz ustawienia</Button></section>
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Market assumptions</h2><p className="mt-1 text-sm text-muted-foreground">Używane tylko, gdy brak wystarczających comps. Każda wartość ma provenance USER_ASSUMPTION.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Text label="Miasto" value={market.city} onChange={(value) => setMarket((current) => ({ ...current, city: value }))} /><Text label="Dzielnica (opcjonalnie)" value={market.district} onChange={(value) => setMarket((current) => ({ ...current, district: value }))} /><Text label="Typ budynku (opcjonalnie)" value={market.buildingType} onChange={(value) => setMarket((current) => ({ ...current, buildingType: value }))} /><Text numeric label="Metraż od" value={market.areaMin} onChange={(value) => setMarket((current) => ({ ...current, areaMin: value }))} /><Text numeric label="Metraż do" value={market.areaMax} onChange={(value) => setMarket((current) => ({ ...current, areaMax: value }))} /><Text numeric label="Pokoje" value={market.rooms} onChange={(value) => setMarket((current) => ({ ...current, rooms: value }))} /><Text numeric label="LOW zł/m²" value={market.low} onChange={(value) => setMarket((current) => ({ ...current, low: value }))} /><Text numeric label="BASE zł/m²" value={market.base} onChange={(value) => setMarket((current) => ({ ...current, base: value }))} /><Text numeric label="HIGH zł/m²" value={market.high} onChange={(value) => setMarket((current) => ({ ...current, high: value }))} /><Text numeric label="Confidence" value={market.confidence} onChange={(value) => setMarket((current) => ({ ...current, confidence: value }))} /></div><Button className="mt-4" onClick={() => void saveMarket()} type="button">Dodaj założenie</Button>{assumptions.length ? <ul className="mt-4 divide-y text-sm">{assumptions.slice(0, 8).map((assumption) => <li className="py-2" key={assumption.id}>{[assumption.city, assumption.district, assumption.building_type, assumption.area_min != null || assumption.area_max != null ? `${assumption.area_min ?? "*"}–${assumption.area_max ?? "*"} m²` : null, assumption.rooms ? `${assumption.rooms} pok.` : null].filter(Boolean).join(" · ")} — {assumption.resale_price_per_m2_low}/{assumption.resale_price_per_m2_base}/{assumption.resale_price_per_m2_high} zł/m² · {assumption.confidence}%</li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">Brak ręcznych założeń. MARKET użyje comps albo będzie BLOCKED.</p>}</section>
    {message ? <p className="text-sm font-medium">{message}</p> : null}
  </div>;
}

function mutation(method: "POST" | "PUT", body: unknown): RequestInit { return { method, headers: { "content-type": "application/json", "x-flip-finder-action": "investment-os" }, body: JSON.stringify(body) }; }
function Setting({ label, value, onChange }: { label: string; value: number; onChange: (value: string) => void }) { return <Text numeric label={label} value={String(value)} onChange={onChange} />; }
function Text({ label, value, numeric, onChange }: { label: string; value: string; numeric?: boolean; onChange: (value: string) => void }) { return <label><span className="mb-1 block text-xs text-muted-foreground">{label}</span><Input min={numeric ? "0" : undefined} onChange={(event) => onChange(event.target.value)} type={numeric ? "number" : "text"} value={value} /></label>; }
function optionalNumber(value: string): number | null { const parsed = Number(value); return value.trim() && Number.isFinite(parsed) ? parsed : null; }
