"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DEFAULT_UNDERWRITING_SETTINGS, type UnderwritingSettings } from "@/features/flip-finder/underwriting";

type Assumption = { id: string; city: string; district: string | null; building_type: string | null; resale_price_per_m2_low: number; resale_price_per_m2_base: number; resale_price_per_m2_high: number; confidence: number };

export function InvestmentOsSettings() {
  const [settings, setSettings] = useState(DEFAULT_UNDERWRITING_SETTINGS); const [assumptions, setAssumptions] = useState<Assumption[]>([]); const [message, setMessage] = useState<string | null>(null);
  const [market, setMarket] = useState({ city: "Łódź", district: "", buildingType: "", low: "", base: "", high: "", confidence: "70" });
  useEffect(() => { void Promise.all([fetch("/api/flip-finder/investment/settings").then((r) => r.json()), fetch("/api/flip-finder/investment/market-assumptions").then((r) => r.json())]).then(([s, a]) => { if (s.settings) setSettings(s.settings); if (Array.isArray(a.assumptions)) setAssumptions(a.assumptions); }).catch(() => setMessage("Nie udało się pobrać ustawień Investment OS.")); }, []);
  const update = (key: keyof UnderwritingSettings, raw: string) => { const value = Number(raw); if (!Number.isFinite(value) || value < 0) return; setSettings((current) => ({ ...current, [key]: value })); };
  const updateRenovation = (key: keyof UnderwritingSettings["renovationPerM2"], raw: string) => { const value = Number(raw); if (!Number.isFinite(value) || value < 0) return; setSettings((current) => ({ ...current, renovationPerM2: { ...current.renovationPerM2, [key]: value } })); };
  const saveSettings = async () => { const response = await fetch("/api/flip-finder/investment/settings", { method: "PUT", headers: { "content-type": "application/json", "x-flip-finder-action": "investment-os" }, body: JSON.stringify(settings) }); setMessage(response.ok ? "Ustawienia zapisane. UNDERWRITER i CEO oznaczono jako STALE." : "Nie udało się zapisać ustawień."); };
  const saveMarket = async () => { const response = await fetch("/api/flip-finder/investment/market-assumptions", { method: "POST", headers: { "content-type": "application/json", "x-flip-finder-action": "investment-os" }, body: JSON.stringify({ ...market, low: Number(market.low), base: Number(market.base), high: Number(market.high), confidence: Number(market.confidence) }) }); const body = await response.json(); if (response.ok && body.assumption) { setAssumptions((current) => [body.assumption, ...current]); setMessage("Założenie rynku zapisane. Dotknięte deale oznaczono jako STALE."); } else setMessage("Sprawdź zakres LOW ≤ BASE ≤ HIGH i confidence 0–100."); };
  return <div className="space-y-6">
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Koszt remontu i finansowanie</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Setting label="LIGHT zł/m²" value={settings.renovationPerM2.LIGHT} onChange={(v) => updateRenovation("LIGHT", v)} /><Setting label="STANDARD zł/m²" value={settings.renovationPerM2.STANDARD} onChange={(v) => updateRenovation("STANDARD", v)} /><Setting label="FULL zł/m²" value={settings.renovationPerM2.FULL} onChange={(v) => updateRenovation("FULL", v)} /><Setting label="Oprocentowanie roczne %" value={settings.financingAnnualRatePercent} onChange={(v) => update("financingAnnualRatePercent", v)} /><Setting label="Finansowany udział %" value={settings.financingLoanPercent} onChange={(v) => update("financingLoanPercent", v)} /><label className="flex items-center gap-2 rounded-lg border px-3"><input checked={settings.financingEnabled} onChange={(event) => setSettings((current) => ({ ...current, financingEnabled: event.target.checked }))} type="checkbox" />Uwzględnij finansowanie</label></div></section>
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Flip Investment OS · Underwriting</h2><p className="mt-1 text-sm text-muted-foreground">Centralne, trwałe założenia. Wyniki finansowe są liczone na serwerze, nie przyjmowane od klienta.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Setting label="Rezerwa %" value={settings.contingencyPercent} onChange={(v) => update("contingencyPercent", v)} /><Setting label="Koszt zakupu %" value={settings.purchaseTaxPercent} onChange={(v) => update("purchaseTaxPercent", v)} /><Setting label="Koszty stałe zakupu" value={settings.fixedPurchaseCosts} onChange={(v) => update("fixedPurchaseCosts", v)} /><Setting label="Koszt sprzedaży %" value={settings.salesCostPercent} onChange={(v) => update("salesCostPercent", v)} /><Setting label="Miesiące utrzymania" value={settings.holdingMonths} onChange={(v) => update("holdingMonths", v)} /><Setting label="Utrzymanie / miesiąc" value={settings.monthlyHoldingCost} onChange={(v) => update("monthlyHoldingCost", v)} /><Setting label="Minimalny zysk" value={settings.minimumProfitPLN} onChange={(v) => update("minimumProfitPLN", v)} /><Setting label="Minimalna marża %" value={settings.minimumMarginPercent} onChange={(v) => update("minimumMarginPercent", v)} /><Setting label="Minimalne ROI %" value={settings.minimumROI} onChange={(v) => update("minimumROI", v)} /><Setting label="Bufor negocjacyjny %" value={settings.targetNegotiationBufferPercent} onChange={(v) => update("targetNegotiationBufferPercent", v)} /></div><Button className="mt-4" onClick={() => void saveSettings()} type="button">Zapisz ustawienia</Button></section>
    <section className="rounded-xl border bg-card p-5"><h2 className="text-lg font-bold">Market assumptions</h2><p className="mt-1 text-sm text-muted-foreground">Używane tylko, gdy brak wystarczających comps. Każda wartość ma provenance USER_ASSUMPTION.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Text label="Miasto" value={market.city} onChange={(v) => setMarket((c) => ({ ...c, city: v }))} /><Text label="Dzielnica (opcjonalnie)" value={market.district} onChange={(v) => setMarket((c) => ({ ...c, district: v }))} /><Text label="Typ budynku (opcjonalnie)" value={market.buildingType} onChange={(v) => setMarket((c) => ({ ...c, buildingType: v }))} /><Text label="LOW zł/m²" numeric value={market.low} onChange={(v) => setMarket((c) => ({ ...c, low: v }))} /><Text label="BASE zł/m²" numeric value={market.base} onChange={(v) => setMarket((c) => ({ ...c, base: v }))} /><Text label="HIGH zł/m²" numeric value={market.high} onChange={(v) => setMarket((c) => ({ ...c, high: v }))} /><Text label="Confidence" numeric value={market.confidence} onChange={(v) => setMarket((c) => ({ ...c, confidence: v }))} /></div><Button className="mt-4" onClick={() => void saveMarket()} type="button">Dodaj założenie</Button>{assumptions.length ? <ul className="mt-4 divide-y text-sm">{assumptions.slice(0, 8).map((a) => <li className="py-2" key={a.id}>{[a.city, a.district, a.building_type].filter(Boolean).join(" · ")} — {a.resale_price_per_m2_low}/{a.resale_price_per_m2_base}/{a.resale_price_per_m2_high} zł/m² · {a.confidence}%</li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">Brak ręcznych założeń. MARKET użyje comps albo będzie BLOCKED.</p>}</section>
    {message ? <p className="text-sm font-medium">{message}</p> : null}
  </div>;
}
function Setting({ label, value, onChange }: { label: string; value: number; onChange: (value: string) => void }) { return <Text label={label} numeric value={String(value)} onChange={onChange} />; }
function Text({ label, value, numeric, onChange }: { label: string; value: string; numeric?: boolean; onChange: (value: string) => void }) { return <label><span className="mb-1 block text-xs text-muted-foreground">{label}</span><Input min={numeric ? "0" : undefined} onChange={(event) => onChange(event.target.value)} type={numeric ? "number" : "text"} value={value} /></label>; }
