import type { CanonicalDeal } from "../types";
import { formatPercentDisplay, formatPLNDisplay, MetricTile, PanelCard } from "./investment-ui";

export function MarketPanel({ deal }: { deal: CanonicalDeal }) {
  const market = deal.market.result;
  if (!market) return <BlockedPanel title="Dane rynkowe" />;
  return <div className="space-y-4">
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><MetricTile label="Odsprzedaż · ostrożna" value={money(market.resaleValueLow)} detail={`${money(market.resalePricePerM2Low)} / m²`} /><MetricTile label="Odsprzedaż · bazowa" value={money(market.resaleValueBase)} detail={`${money(market.resalePricePerM2Base)} / m²`} emphasis /><MetricTile label="Odsprzedaż · optymistyczna" value={money(market.resaleValueHigh)} detail={`${money(market.resalePricePerM2High)} / m²`} /></div>
    <PanelCard title="Jakość i aktualność danych rynkowych"><p>Źródło dopasowania: {marketMatchLabel(market.assumptionMatchedBy)} · rodzaj dowodu: {evidenceLabel(market.priceEvidenceType)} · porównania: {market.compCount}</p><p className="mt-1">Pewność: {formatPercentDisplay(deal.market.confidence, 0)} · dane zastępcze: {fallbackLabel(deal.market.fallbackLevel)}</p><p className="mt-1">Odczytano: {dateLabel(market.observedAt)} · aktualne do: {dateLabel(deal.market.freshUntil)}</p></PanelCard>
    <section><h4 className="type-card-title">Najważniejsze porównania</h4>{market.comparables.length ? <div className="mt-2 grid gap-2 md:grid-cols-2">{market.comparables.slice(0, 5).map((comp) => <article className="rounded-2xl border border-border/70 bg-background/35 p-3 text-sm" key={comp.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{sourceLabel(comp.source)}</p><p className="type-financial-standard text-foreground">{money(comp.pricePerM2)} / m²</p></div><p className="mt-1 text-xs text-muted-foreground">Podobieństwo {formatPercentDisplay(comp.similarityScore, 0)} · jakość danych {formatPercentDisplay(comp.dataQuality, 0)} · waga {new Intl.NumberFormat("pl-PL", { maximumFractionDigits: 2 }).format(comp.weight)} · aktualność {comp.freshnessDays == null ? "—" : `${comp.freshnessDays} dni`}{comp.distanceMeters == null ? "" : ` · ${comp.distanceMeters} m`}</p>{comp.sourceUrl ? <a className="mt-2 inline-flex min-h-8 items-center font-medium text-primary underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href={comp.sourceUrl} rel="noreferrer" target="_blank">Otwórz źródło</a> : null}{comp.adjustments.length ? <p className="mt-1 text-xs text-muted-foreground">Uwzględnione dopasowania: {comp.adjustments.length}</p> : null}{comp.outlierReason ? <p className="mt-1 text-xs text-amber-700 dark:text-amber-300">Oznaczono wartość jako odstającą.</p> : null}</article>)}</div> : <p className="mt-2 text-sm text-muted-foreground">Brak porównań w bieżącym wyniku.</p>}</section>
  </div>;
}

function BlockedPanel({ title }: { title: string }) { return <div className="rounded-2xl border border-amber-500/30 bg-amber-500/[0.07] p-4"><p className="type-card-title">{title} · do uzupełnienia</p><p className="mt-1 text-sm text-muted-foreground">Nie ma wystarczających danych rynkowych. Wróć po dodaniu porównań lub założeń.</p></div>; }
function money(value: number | null | undefined) { return formatPLNDisplay(value); }
function fallbackLabel(value: number): string { return value === 0 ? "bez danych zastępczych" : `poziom ${new Intl.NumberFormat("pl-PL", { maximumFractionDigits: 0 }).format(value)}`; }
function dateLabel(value: string | null | undefined): string { if (!value) return "nie ustalono"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "nie ustalono" : new Intl.DateTimeFormat("pl-PL", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function sourceLabel(value: string): string { return ({ OTODOM: "Otodom", otodom: "Otodom", OLX: "OLX", olx: "OLX", FACEBOOK: "Facebook", facebook: "Facebook", "Oferta porównawcza": "Oferta porównawcza", TRANSACTION: "Dane transakcyjne", RESALE_COMPS: "Porównania odsprzedaży" } as Record<string, string>)[value] ?? "Źródło porównawcze"; }
function marketMatchLabel(value: string | null | undefined) { return ({ RESALE_COMPS: "porównania odsprzedaży", DEAL_OVERRIDE: "korekta ręczna" } as Record<string, string>)[value ?? ""] ?? value ?? "brak"; }
function evidenceLabel(value: "ASKING" | "TRANSACTION" | "MIXED" | "USER_ASSUMPTION") { return ({ ASKING: "ceny ofertowe", TRANSACTION: "dane transakcyjne", MIXED: "dane mieszane", USER_ASSUMPTION: "założenie ręczne" } as const)[value]; }
