import type { CanonicalDeal } from "../types";
import { MetricTile, PanelCard } from "./investment-ui";

export function MarketPanel({ deal }: { deal: CanonicalDeal }) {
  const market = deal.market.result;
  if (!market) return <BlockedPanel title="MARKET" reasons={deal.market.reasonCodes} />;
  return <div className="space-y-4">
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><MetricTile label="Odsprzedaż · low" value={money(market.resaleValueLow)} detail={`${money(market.resalePricePerM2Low)} / m²`} /><MetricTile label="Odsprzedaż · base" value={money(market.resaleValueBase)} detail={`${money(market.resalePricePerM2Base)} / m²`} emphasis /><MetricTile label="Odsprzedaż · high" value={money(market.resaleValueHigh)} detail={`${money(market.resalePricePerM2High)} / m²`} /></div>
    <PanelCard title="Jakość i świeżość rynku"><p>Źródło dopasowania: {market.assumptionMatchedBy || "brak"} · typ evidence: {market.priceEvidenceType} · comparables: {market.compCount}</p><p className="mt-1">Confidence: {deal.market.confidence}% · fallback L{deal.market.fallbackLevel}: {deal.market.fallbackReason ?? "brak"}</p><p className="mt-1">Obserwacja: {market.observedAt ?? "nieustalona"} · dane ważne do: {deal.market.freshUntil ?? "nieustalone"}</p></PanelCard>
    <section><h4 className="text-sm font-semibold">Najważniejsze porównania</h4>{market.comparables.length ? <div className="mt-2 grid gap-2 md:grid-cols-2">{market.comparables.slice(0, 5).map((comp) => <article className="rounded-lg border border-border/70 p-3 text-sm" key={comp.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{comp.source}</p><p className="font-semibold tabular-nums text-foreground">{money(comp.pricePerM2)} / m²</p></div><p className="mt-1 text-xs text-muted-foreground">Podobieństwo {comp.similarityScore} · jakość {comp.dataQuality} · waga {comp.weight} · świeżość {comp.freshnessDays == null ? "—" : `${comp.freshnessDays} dni`}{comp.distanceMeters == null ? "" : ` · ${comp.distanceMeters} m`}</p>{comp.sourceUrl ? <a className="mt-2 inline-flex min-h-8 items-center font-medium text-primary underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href={comp.sourceUrl} rel="noreferrer" target="_blank">Otwórz źródło</a> : null}{comp.adjustments.length ? <p className="mt-1 text-xs text-muted-foreground">Korekty: {comp.adjustments.join(", ")}</p> : null}{comp.outlierReason ? <p className="mt-1 text-xs text-amber-700 dark:text-amber-300">Outlier: {comp.outlierReason}</p> : null}</article>)}</div> : <p className="mt-2 text-sm text-muted-foreground">Brak porównań w bieżącym wyniku.</p>}</section>
  </div>;
}

function BlockedPanel({ title, reasons }: { title: string; reasons: string[] }) { return <div className="rounded-lg border border-amber-500/30 bg-amber-500/[0.07] p-4"><p className="font-semibold">{title} · BLOCKED</p><p className="mt-1 text-sm text-muted-foreground">{reasons.join(" · ") || "Brak danych do obliczenia."}</p></div>; }
function money(value: number | null | undefined) { return value == null ? "—" : new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN", maximumFractionDigits: 0 }).format(value); }
