"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ExternalLink, Filter, Flame, Plus, Search, Star, Undo2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ExpandableListingCard } from "@/features/flip-finder/components/inline-filter-results";
import type { FilterResult } from "@/features/flip-finder/results";
import { EMPTY_FACEBOOK_INBOX_FILTERS, filterFacebookInbox, opportunityLabel, sortFacebookInbox, type FacebookInboxFilters, type FacebookInboxSort } from "../facebook-inbox";
import type { FacebookWatcherListing, FacebookWorkflowStatus } from "../types";

type InboxTab = FacebookWorkflowStatus | "all";
const TABS: Array<{ value: InboxTab; label: string }> = [{value:"all",label:"Wszystkie"},{value:"new",label:"Nowe"},{value:"review",label:"Do analizy"},{value:"interesting",label:"Okazje"},{value:"crm",label:"Dodane do CRM"},{value:"rejected",label:"Odrzucone"}];
const STATUS_LABELS: Record<FacebookWorkflowStatus,string> = {new:"Nowa",review:"Do analizy",interesting:"Interesująca",crm:"W CRM",rejected:"Odrzucona"};

export function FacebookWatcherPanel() {
  const handledDeepLink=useRef(false);
  const [listings,setListings]=useState<FacebookWatcherListing[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [tab,setTab]=useState<InboxTab>("all"); const [sort,setSort]=useState<FacebookInboxSort>("newest"); const [filters,setFilters]=useState<FacebookInboxFilters>(EMPTY_FACEBOOK_INBOX_FILTERS); const [busyId,setBusyId]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{let active=true;fetch("/api/facebook-watcher/listings",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??"Nie udało się pobrać Inboxu.");if(active)setListings(body.listings??[]);}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Nie udało się pobrać Inboxu.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  useEffect(()=>{if(handledDeepLink.current||!listings.length)return;const listingId=new URLSearchParams(window.location.search).get("listing");if(!listingId)return;handledDeepLink.current=true;const timeout=window.setTimeout(()=>document.querySelector<HTMLElement>(`#facebook-inbox-${CSS.escape(listingId)} [role=button]`)?.click(),0);return()=>window.clearTimeout(timeout);},[listings]);
  const visible=useMemo(()=>sortFacebookInbox(filterFacebookInbox(listings,tab,filters),sort),[filters,listings,sort,tab]);
  const top=useMemo(()=>sortFacebookInbox(listings.filter(item=>item.workflowStatus!=="rejected"),"opportunity").slice(0,10),[listings]);
  const today=listings.filter(item=>item.isNew).length; const review=listings.filter(item=>item.workflowStatus==="review").length; const priority=listings.filter(item=>item.highPriority).length; const crm=listings.filter(item=>item.workflowStatus==="crm").length; const rejected=listings.filter(item=>item.workflowStatus==="rejected").length;
  const updateWorkflow=async(item:FacebookWatcherListing,change:{status?:FacebookWorkflowStatus;markRead?:boolean;crmPropertyId?:string})=>{setBusyId(item.listingId);setMessage(null);try{const response=await fetch(`/api/facebook-watcher/listings/${item.listingId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(change)});const body=await response.json();if(!response.ok)throw new Error(body.error??"Nie udało się zmienić statusu.");setListings(current=>current.map(value=>value.listingId===item.listingId?{...value,...(change.status?{workflowStatus:change.status}:{}),...(change.markRead?{readAt:new Date().toISOString(),isNew:false}:{})}:value));}catch(reason){setMessage(reason instanceof Error?reason.message:"Nie udało się zmienić statusu.");}finally{setBusyId(null);}};
  const addToCrm=async(item:FacebookWatcherListing)=>{setBusyId(item.listingId);setMessage(null);try{const result=toFilterResult(item);const response=await fetch("/api/properties/import-from-finder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...result,investmentAnalysis:null})});const body=await response.json();if(!response.ok||typeof body.propertyId!=="string")throw new Error(body.message??"Nie udało się dodać oferty do CRM.");await updateWorkflow(item,{status:"crm",crmPropertyId:body.propertyId});setMessage(body.status==="updated"?"Oferta była już w CRM — rekord został zaktualizowany.":"Oferta została dodana do CRM.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Nie udało się dodać oferty do CRM.");setBusyId(null);}};
  const openAnalysis=(id:string)=>document.querySelector<HTMLElement>(`#facebook-inbox-${CSS.escape(id)} [role=button]`)?.click();
  return <main className="mx-auto w-full max-w-[1500px] space-y-7 px-4 py-5 sm:px-6 lg:px-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-gold/25 bg-gold/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.16em] text-gold"><Flame className="size-3.5"/>Premium inbox</div><h1 className="font-heading text-3xl font-bold tracking-tight">Facebook Watcher / Inbox</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Jedno miejsce do przeglądania, analizowania i przekazywania ofert Facebooka do CRM.</p></div><div className="flex flex-wrap gap-2"><Button nativeButton={false} variant="outline" render={<Link href="/flip-finder/facebook/groups"/>} className="min-h-11">Obserwowane grupy</Button><Button nativeButton={false} render={<Link href="/properties/new"/>} className="min-h-11"><Plus className="size-4"/>Dodaj post z Facebooka</Button></div></header>
    <section aria-label="Liczniki Inboxu" className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5"><Counter label="Nowe dziś" value={today}/><Counter label="Do analizy" value={review}/><Counter label="Wysoki priorytet" tone="fire" value={priority}/><Counter label="Dodane do CRM" value={crm}/><Counter label="Odrzucone" value={rejected}/></section>
    <nav aria-label="Status ofert Facebook" className="-mx-4 flex snap-x gap-2 overflow-x-auto px-4 pb-1 sm:mx-0 sm:px-0">{TABS.map(item=><button aria-pressed={tab===item.value} className={`min-h-11 shrink-0 snap-start rounded-xl border px-4 text-sm font-semibold ${tab===item.value?"border-gold/40 bg-gold/15 text-gold":"border-border bg-card text-muted-foreground hover:text-foreground"}`} key={item.value} onClick={()=>setTab(item.value)}>{item.label}<span className="ml-2 rounded-full bg-black/15 px-2 py-0.5 text-xs">{item.value==="all"?listings.length:listings.filter(value=>value.workflowStatus===item.value).length}</span></button>)}</nav>
    {top.length?<section className="ui-section"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-heading text-xl font-bold">Najlepsze okazje z Facebooka</h2><p className="mt-1 text-xs text-muted-foreground">TOP 10 według Opportunity Score</p></div><Star className="size-5 text-gold"/></div><div className="-mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-2">{top.map(item=><button className="ui-card ui-card-hover w-64 shrink-0 snap-start overflow-hidden text-left" key={item.listingId} onClick={()=>{setTab("all");setFilters({...EMPTY_FACEBOOK_INBOX_FILTERS,query:item.title});}}>{item.images[0]?<div className="relative aspect-[16/9]"><Image fill unoptimized alt="" className="object-cover" sizes="256px" src={item.images[0]}/></div>:null}<div className="p-3"><p className="line-clamp-2 text-sm font-semibold">{item.title}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs text-muted-foreground">{opportunityLabel(item.opportunityScore)??"Obserwowana"}</span><strong className="text-gold">{item.opportunityScore}</strong></div></div></button>)}</div></section>:null}
    <section className="space-y-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_240px_auto]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-muted-foreground"/><Input aria-label="Szukaj ofert Facebook" className="h-11 pl-10" placeholder="Szukaj: tytuł, opis, ulica, osiedle, grupa" value={filters.query} onChange={event=>setFilters(current=>({...current,query:event.target.value}))}/></label><select aria-label="Sortowanie" className="h-11 rounded-xl border border-input bg-background px-3 text-sm" value={sort} onChange={event=>setSort(event.target.value as FacebookInboxSort)}><option value="newest">Najnowsze</option><option value="opportunity">Najwyższy Opportunity Score</option><option value="flip">Najwyższy Flip Score</option><option value="price_per_sqm">Najniższa cena/m²</option><option value="price">Najniższa cena</option><option value="profit">Największy potencjalny zysk</option></select><details className="relative md:hidden"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-center gap-2 rounded-xl border bg-card px-4 text-sm font-semibold"><Filter className="size-4"/>Filtry</summary><div className="mt-2 rounded-xl border bg-card p-4"><FilterControls filters={filters} listings={listings} setFilters={setFilters}/></div></details></div><div className="hidden rounded-2xl border border-border/70 bg-card p-4 md:block"><FilterControls filters={filters} listings={listings} setFilters={setFilters}/></div>
      <div className="flex items-center justify-between text-sm text-muted-foreground"><span>Wyniki: <strong className="text-foreground">{visible.length}</strong></span>{message?<span aria-live="polite" className="text-foreground">{message}</span>:null}</div>
      {error?<p className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</p>:null}{loading?<p className="py-12 text-center text-sm text-muted-foreground">Ładowanie Inboxu…</p>:null}
      {!loading&&visible.length===0?<div className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">Brak ofert spełniających wybrane kryteria.</div>:null}
      <div className="grid gap-5 xl:grid-cols-2">{visible.map(item=><InboxItem addToCrm={addToCrm} busy={busyId===item.listingId} item={item} key={item.listingId} onAnalyze={openAnalysis} updateWorkflow={updateWorkflow}/>)}</div>
    </section>
  </main>;
}

function InboxItem({item,busy,updateWorkflow,addToCrm,onAnalyze}:{item:FacebookWatcherListing;busy:boolean;updateWorkflow:(item:FacebookWatcherListing,change:{status?:FacebookWorkflowStatus;markRead?:boolean;crmPropertyId?:string})=>Promise<void>;addToCrm:(item:FacebookWatcherListing)=>Promise<void>;onAnalyze:(id:string)=>void}) { const result=toFilterResult(item); return <article className="space-y-2" id={`facebook-inbox-${item.listingId}`}><div className="rounded-2xl border border-border/70 bg-card px-3 py-3"><div className="flex flex-wrap items-center gap-2"><WorkflowBadge status={item.workflowStatus}/>{item.isNew?<Badge text="NOWA" tone="gold"/>:null}{item.highPriority?<Badge text="🔥 Wysoki priorytet" tone="fire"/>:null}{item.sellerType==="private"?<Badge text="Prywatny właściciel"/>:null}{item.condition==="renovation"?<Badge text="Do remontu"/>:null}{item.flags.filter(flag=>/bez pośred|pilne/i.test(flag)).slice(0,2).map(flag=><Badge key={flag} text={flag}/>)}</div><div className="mt-3 grid gap-1 text-xs text-muted-foreground sm:grid-cols-2"><span>Publikacja: {dateTime(item.publishedAt)}</span><span>Import: {dateTime(item.importedAt)}</span><span>Grupa: {item.groupName??"Facebook"}</span><span>Opportunity Score: <strong className="text-gold">{item.opportunityScore}</strong> · Flip Score: <strong className="text-foreground">{item.flipScore}</strong></span></div>{item.crossSourceLinks.length?<div className="mt-2 flex flex-wrap gap-2">{item.crossSourceLinks.map(link=><a className="text-xs font-semibold text-sky-400 hover:underline" href={link.url} key={link.url} rel="noopener noreferrer" target="_blank">Znaleziona też na {sourceName(link.source)} ↗</a>)}</div>:null}<div className="mt-3 flex gap-2 overflow-x-auto pb-1"><Action disabled={busy} label="Analizuj" onClick={()=>onAnalyze(item.listingId)}/><Action disabled={busy} label="Interesująca" onClick={()=>void updateWorkflow(item,{status:"interesting"})}/><Action disabled={busy} label="Dodaj do CRM" onClick={()=>void addToCrm(item)}/>{item.workflowStatus==="rejected"?<Action disabled={busy} icon={<Undo2 className="size-3.5"/>} label="Przywróć" onClick={()=>void updateWorkflow(item,{status:"review"})}/>:<Action disabled={busy} icon={<XCircle className="size-3.5"/>} label="Odrzuć" onClick={()=>void updateWorkflow(item,{status:"rejected"})}/>} {item.originalUrl?<a className="flex min-h-11 shrink-0 items-center gap-1.5 rounded-lg border px-3 text-xs font-semibold" href={item.originalUrl} rel="noopener noreferrer" target="_blank"><ExternalLink className="size-3.5"/>Facebook</a>:null}</div></div><ExpandableListingCard averagePricePerSqm={null} marketType={item.marketType} onCrmImported={propertyId=>void updateWorkflow(item,{status:"crm",crmPropertyId:propertyId})} onOpen={()=>{if(!item.readAt)void updateWorkflow(item,{markRead:true});}} result={result}/></article>; }

function FilterControls({filters,listings,setFilters}:{filters:FacebookInboxFilters;listings:FacebookWatcherListing[];setFilters:React.Dispatch<React.SetStateAction<FacebookInboxFilters>>}) { const update=<K extends keyof FacebookInboxFilters>(key:K,value:FacebookInboxFilters[K])=>setFilters(current=>({...current,[key]:value})); const options=(key:"neighborhood"|"district"|"groupName")=>[...new Set(listings.map(item=>item[key]).filter((value):value is string=>Boolean(value)))].sort((a,b)=>a.localeCompare(b,"pl")); return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Select label="Osiedle" value={filters.neighborhood} onChange={value=>update("neighborhood",value)} options={options("neighborhood")}/><Select label="Dzielnica" value={filters.district} onChange={value=>update("district",value)} options={options("district")}/><Select label="Grupa" value={filters.group} onChange={value=>update("group",value)} options={options("groupName")}/><NumberFilter label="Cena maks." value={filters.maxPrice} onChange={value=>update("maxPrice",value)}/><NumberFilter label="Cena/m² maks." value={filters.maxPricePerSqm} onChange={value=>update("maxPricePerSqm",value)}/><NumberFilter label="Pokoje" value={filters.rooms} onChange={value=>update("rooms",value)}/><NumberFilter label="Flip Score min." value={filters.minFlipScore} onChange={value=>update("minFlipScore",value)}/><NumberFilter label="Opportunity min." value={filters.minOpportunityScore} onChange={value=>update("minOpportunityScore",value)}/><Select label="Sprzedający" value={filters.sellerType} onChange={value=>update("sellerType",value as FacebookInboxFilters["sellerType"])} options={["private","agency"]} labels={{private:"Prywatny",agency:"Pośrednik"}}/><Select label="Stan" value={filters.condition} onChange={value=>update("condition",value as FacebookInboxFilters["condition"])} options={["renovation","ready"]} labels={{renovation:"Do remontu",ready:"Do wejścia"}}/><Select label="Data publikacji" value={filters.publishedDays?.toString()??""} onChange={value=>update("publishedDays",value?Number(value):null)} options={["1","7","30","90"]} labels={{"1":"24 godziny","7":"7 dni","30":"30 dni","90":"90 dni"}}/><button className="min-h-11 self-end rounded-xl border px-3 text-sm font-semibold" onClick={()=>setFilters({...EMPTY_FACEBOOK_INBOX_FILTERS,query:filters.query})}>Wyczyść filtry</button></div>; }
function Counter({label,value,tone}:{label:string;value:number;tone?:"fire"}){return <div className={`ui-card p-4 ${tone==="fire"?"border-orange-500/25 bg-orange-500/[0.06]":""}`}><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 font-mono text-2xl font-bold ${tone==="fire"?"text-orange-400":""}`}>{value}</p></div>}
function WorkflowBadge({status}:{status:FacebookWorkflowStatus}){return <Badge text={STATUS_LABELS[status]} tone={status==="interesting"?"gold":status==="rejected"?"fire":undefined}/>}
function Badge({text,tone}:{text:string;tone?:"gold"|"fire"}){return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${tone==="gold"?"border-gold/30 bg-gold/10 text-gold":tone==="fire"?"border-orange-500/30 bg-orange-500/10 text-orange-400":"border-border bg-muted text-muted-foreground"}`}>{text}</span>}
function Action({label,onClick,disabled,icon}:{label:string;onClick:()=>void;disabled:boolean;icon?:React.ReactNode}){return <button className="flex min-h-11 shrink-0 items-center gap-1.5 rounded-lg border px-3 text-xs font-semibold hover:border-gold/40 hover:text-gold disabled:opacity-50" disabled={disabled} onClick={onClick}>{icon}{label}</button>}
function Select({label,value,onChange,options,labels={}}:{label:string;value:string;onChange:(value:string)=>void;options:string[];labels?:Record<string,string>}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}<select className="h-11 rounded-xl border bg-background px-2 text-sm text-foreground" value={value} onChange={event=>onChange(event.target.value)}><option value="">Wszystkie</option>{options.map(option=><option key={option} value={option}>{labels[option]??option}</option>)}</select></label>}
function NumberFilter({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}<input className="h-11 rounded-xl border bg-background px-3 text-sm text-foreground" min="0" type="number" value={value??""} onChange={event=>onChange(event.target.value?Number(event.target.value):null)}/></label>}
function dateTime(value:string|null){return value?new Intl.DateTimeFormat("pl-PL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"brak"}
function sourceName(value:string){return value==="olx"?"OLX":value==="otodom"?"Otodom":value==="morizon"?"Morizon":value}
function toFilterResult(item:FacebookWatcherListing):FilterResult { const eventAt=item.publishedAt??item.importedAt; return {id:item.listingId,title:item.title,price:item.price,area:item.area,rooms:item.rooms,floor:item.floor===null?null:String(item.floor),totalFloors:item.totalFloors===null?null:String(item.totalFloors),buildingType:null,ownership:null,description:item.description,images:item.images,pricePerSqm:item.pricePerSqm,locationText:[item.street,item.neighborhood,item.district,item.city].filter(Boolean).join(", "),address:item.street,city:item.city,district:item.district,thumbnailUrl:item.images[0]??null,originalUrl:item.originalUrl??"https://www.facebook.com/",source:"facebook",listingStatus:item.status==="removed"||item.status==="sold"||item.status==="watched"?item.status:"active",isActive:item.status==="active",publishedAt:item.publishedAt,firstSeenAt:item.importedAt,lastSeenAt:eventAt,firstMatchedAt:item.importedAt,lastMatchedAt:item.importedAt,previousPrice:null,currentPrice:item.price,isNew:item.isNew,hasPriceDrop:false,priceDropAmount:null,matchReasons:item.flags,unknownFields:[]}; }
