"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ExternalLink, Plus, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { FacebookGroupInput, WatchedFacebookGroup } from "../types";

const initial: FacebookGroupInput = { name: "", url: "", city: "Łódź", district: null, neighborhood: null, priority: "high", keywords: ["sprzedam", "bezpośrednio", "bez pośredników", "do remontu", "po babci", "pilnie", "okazja", "do negocjacji"], enabled: true };

export function WatchedGroupsPage() {
  const [groups, setGroups] = useState<WatchedFacebookGroup[]>([]); const [form, setForm] = useState(initial); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { const response = await fetch("/api/facebook-watcher/groups", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setGroups(body.groups); };
  useEffect(() => { let active=true;void fetch("/api/facebook-watcher/groups",{cache:"no-store"}).then(response=>response.json().then(body=>({response,body}))).then(({response,body})=>{if(!response.ok)throw new Error(body.error);if(active)setGroups(body.groups);}).catch(value=>{if(active)setError(value instanceof Error?value.message:"Nie udało się pobrać grup.")});return()=>{active=false}; }, []);
  const create = async () => { setBusy(true); setError(null); try { const response = await fetch("/api/facebook-watcher/groups", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setGroups(current => [...current, body.group]); setForm(initial); } catch (value) { setError(value instanceof Error ? value.message : "Nie udało się dodać grupy."); } finally { setBusy(false); } };
  const toggle = async (group: WatchedFacebookGroup) => { const response = await fetch(`/api/facebook-watcher/groups/${group.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !group.enabled }) }); const body = await response.json(); if (response.ok) setGroups(current => current.map(item => item.id === group.id ? body.group : item)); };
  return <main className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-gold">Facebook Group Watcher</p><h1 className="mt-2 text-3xl font-bold">Obserwowane grupy</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Grupy są źródłami inwestora. Flip Manager nie omija logowania ani zabezpieczeń Facebooka; bez autoryzowanego adaptera korzysta z ręcznego importu.</p></header>
    <section className="ui-section"><h2 className="text-lg font-bold">Dodaj grupę</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Nazwa" value={form.name} onChange={name => setForm(value => ({ ...value, name }))}/><Field label="URL" value={form.url} onChange={url => setForm(value => ({ ...value, url }))}/><Field label="Miasto" value={form.city} onChange={city => setForm(value => ({ ...value, city }))}/><Field label="Dzielnica" value={form.district ?? ""} onChange={district => setForm(value => ({ ...value, district }))}/><Field label="Osiedle" value={form.neighborhood ?? ""} onChange={neighborhood => setForm(value => ({ ...value, neighborhood }))}/><label className="grid gap-1 text-sm">Priorytet<select className="h-11 rounded-xl border bg-background px-3" value={form.priority} onChange={event => setForm(value => ({ ...value, priority: event.target.value as FacebookGroupInput["priority"] }))}><option value="high">Wysoki</option><option value="normal">Normalny</option><option value="low">Niski</option></select></label><label className="grid gap-1 text-sm sm:col-span-2">Frazy<input className="h-11 rounded-xl border bg-background px-3" value={form.keywords.join(", ")} onChange={event => setForm(value => ({ ...value, keywords: event.target.value.split(",").map(item => item.trim()).filter(Boolean) }))}/></label></div>{error ? <p className="mt-3 text-sm text-danger">{error}</p> : null}<Button className="mt-4 min-h-11" disabled={busy || !form.name.trim() || !form.url.trim()} onClick={() => void create()}><Plus className="size-4"/>Dodaj grupę</Button></section>
    <section className="grid gap-4 lg:grid-cols-2">{groups.map(group => <article className="ui-section" key={group.id}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{group.name}</h2><Status value={group.accessStatus}/><span className="rounded-full border px-2 py-1 text-[10px] font-bold uppercase">{group.priority}</span></div><p className="mt-1 text-sm text-muted-foreground">{[group.neighborhood, group.district, group.city].filter(Boolean).join(" • ")}</p></div><button aria-label={group.enabled ? "Wstrzymaj grupę" : "Aktywuj grupę"} className="min-h-11 rounded-xl border px-3 text-xs font-bold" onClick={() => void toggle(group)}>{group.enabled ? "Aktywna" : "Wstrzymana"}</button></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Metric label="Importy" value={group.importedPosts}/><Metric label="Nowe dziś" value={group.newToday}/><Metric label="Okazje" value={group.opportunities}/><Metric label="Ostatnie sprawdzenie" value={group.lastCheckedAt ? new Date(group.lastCheckedAt).toLocaleString("pl-PL") : "—"}/></div>{group.accessStatus !== "CONNECTED" ? <p className="mt-4 rounded-xl border border-warning/30 bg-warning/5 p-3 text-sm text-warning">Ta grupa wymaga ręcznego importu lub autoryzowanego źródła danych.</p> : null}{group.lastError ? <p className="mt-2 text-xs text-danger">{group.lastError}</p> : null}<div className="mt-3 flex flex-wrap gap-3"><a className="flex min-h-11 items-center gap-2 text-sm font-semibold text-gold" href={group.url} target="_blank" rel="noopener noreferrer">Facebook<ExternalLink className="size-4"/></a><Link className="flex min-h-11 items-center gap-2 text-sm font-semibold" href="/properties/new">Import ręczny</Link></div></article>)}{!groups.length ? <div className="ui-section text-sm text-muted-foreground">Nie dodano jeszcze obserwowanych grup.</div> : null}</section>
    <Button variant="outline" onClick={() => void load()}><RefreshCw className="size-4"/>Odśwież</Button></main>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm">{label}<input className="h-11 rounded-xl border bg-background px-3" value={value} onChange={event => onChange(event.target.value)}/></label>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-muted/40 p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
function Status({ value }: { value: WatchedFacebookGroup["accessStatus"] }) { return <span className="rounded-full bg-gold/10 px-2 py-1 text-[10px] font-bold text-gold">{value}</span>; }
