import { calculateUnderwriting, validateMaxPurchaseBoundary, type UnderwritingInput } from "../flip-finder/underwriting.ts";
import { DEFAULT_INVESTMENT_DECISION_POLICY } from "./types.ts";
import { policyFor } from "./tool-policy.ts";
import type { AnalysisLevel, BuildDealInput, CanonicalDeal, CeoResult, DealFacts, DealPlaybook, DirectorExecution, DirectorOutput, EvidenceItem, FactValue, InformationRequest, InvestmentDecisionPolicy, MarketResult, PredictionMetric, ProvenanceEntry, ValidationResult, VerifyResult } from "./types.ts";

export const MATERIAL_FACTS: Array<keyof DealFacts> = ["askingPrice", "areaM2", "rooms", "district", "street", "buildingType", "condition", "ownership"];
export const DIRECTOR_DEPENDENCIES = { SCOUT: [], VERIFY: ["SCOUT"], MARKET: ["VERIFY"], UNDERWRITER: ["MARKET", "VERIFY"], CEO: ["UNDERWRITER", "MARKET", "VERIFY"] } as const;

export function buildCanonicalDeal(input: BuildDealInput): CanonicalDeal {
  const policy = input.policy ?? DEFAULT_INVESTMENT_DECISION_POLICY; const analysisLevel = selectAnalysisLevel(input, policy);
  const facts = buildFacts(input); const factsFingerprint = fingerprint(facts); const provenance = factProvenance(facts);
  const scoutStarted = performance.now(); const scout = output("SCOUT", fingerprint({ id: input.listing.id, source: input.listing.source, url: input.listing.sourceUrl }), input.now, 100, { listingId: input.listing.id, source: facts.source.effectiveValue, sourceUrl: facts.sourceUrl.effectiveValue, lifecycleStatus: input.listing.lifecycleStatus }, [], [], [], provenance.filter((item) => ["source", "sourceUrl", "postId"].includes(item.field)), "COMPLETE", { analysisLevel, elapsedMs: elapsed(scoutStarted) });
  const verifyStarted = performance.now();
  const verified = verifyFacts(facts, input.listing.identityExact, input.listing.conflicts);
  const verifyValidation = validation("VERIFY", input.now, verified.result.conflicts.length ? "FAIL" : "PASS", [{ code: "NO_MATERIAL_FACT_CONFLICT", passed: !verified.result.conflicts.length, detail: verified.result.conflicts.join(",") || "No material conflicts." }]);
  const verify = output("VERIFY", fingerprint({ facts, exact: input.listing.identityExact, conflicts: input.listing.conflicts }), input.now, verified.confidence, verified.result, [...verified.result.missingCriticalFields, ...verified.result.missingOptionalFields], verified.warnings, verified.reasons, provenance, verified.result.conflicts.length ? "BLOCKED" : "COMPLETE", { validation: verifyValidation, analysisLevel, elapsedMs: elapsed(verifyStarted) });
  const market = buildMarket(input, facts, verify, policy, analysisLevel);
  const underwriting = buildUnderwriter(input, facts, market, verify, analysisLevel);
  const ceo = buildCeo(input, facts, verify, market, underwriting, policy, analysisLevel);
  const playbook = buildPlaybook(facts, ceo); const evidenceFabric = buildEvidenceFabric(input, facts, market, underwriting); const informationRequests = ceo.result?.nextBestQuestions ?? [];
  const stage = ceo.status === "COMPLETE" ? "DECISION_READY" : underwriting.status === "COMPLETE" ? "UNDERWRITTEN" : market.status === "COMPLETE" ? "MARKET_READY" : verify.status === "COMPLETE" ? "VERIFIED" : "VERIFYING";
  return { id: input.dealId, listingId: input.listing.id, stage, factsFingerprint, facts, scout, verify, market, underwriting, ceo, playbook, evidenceFabric, informationRequests, analysisLevel, createdAt: input.createdAt ?? input.now, updatedAt: input.now };
}

export function downstreamForChange(changed: Array<keyof DealFacts> | ["MARKET_ASSUMPTION"] | ["UNDERWRITING_SETTINGS"]): Array<"VERIFY" | "MARKET" | "UNDERWRITER" | "CEO"> {
  if (changed[0] === "MARKET_ASSUMPTION") return ["MARKET", "UNDERWRITER", "CEO"];
  if (changed[0] === "UNDERWRITING_SETTINGS") return ["UNDERWRITER", "CEO"];
  return (changed as Array<keyof DealFacts>).some((field) => MATERIAL_FACTS.includes(field)) ? ["VERIFY", "MARKET", "UNDERWRITER", "CEO"] : ["VERIFY", "CEO"];
}
export function fingerprintsEqual(left: CanonicalDeal, right: CanonicalDeal): boolean { return [left.scout, left.verify, left.market, left.underwriting, left.ceo].every((director) => director.version === 3) && left.factsFingerprint === right.factsFingerprint && left.verify.inputFingerprint === right.verify.inputFingerprint && left.market.inputFingerprint === right.market.inputFingerprint && left.underwriting.inputFingerprint === right.underwriting.inputFingerprint && left.ceo.inputFingerprint === right.ceo.inputFingerprint; }

function buildFacts(input: BuildDealInput): DealFacts {
  const l = input.listing; const o = input.overrides;
  const field = <T>(name: keyof DealFacts, sourceValue: T | null, overrideValue: T | null | undefined, derived = false): FactValue<T> => {
    const changed = overrideValue !== undefined && overrideValue !== null; const effectiveValue = changed ? overrideValue! : sourceValue;
    return { sourceValue, overrideValue: changed ? overrideValue! : null, effectiveValue, provenance: changed ? "MANUAL_OVERRIDE" : effectiveValue === null ? "UNKNOWN" : derived ? "DERIVED" : "EXTRACTED", confidence: effectiveValue === null ? 0 : changed ? 100 : derived ? 85 : 90, classification: effectiveValue === null ? "UNKNOWN" : changed ? "USER_OVERRIDE" : derived ? "ESTIMATE" : "FACT", source: changed ? "DEAL_FACT_OVERRIDE" : derived ? "DETERMINISTIC_CALCULATION" : "LISTING", observedAt: l.observedAt, evidenceId: effectiveValue === null ? null : `listing:${l.id}:${String(name)}`, assumptionId: null };
  };
  const ppm = l.askingPricePerM2 ?? (positive(l.askingPrice) !== null && positive(l.areaM2) !== null ? money(l.askingPrice! / l.areaM2!) : null);
  return { city: field("city", l.city, stringOverride(o.city)), district: field("district", l.district, stringOverride(o.district)), street: field("street", l.street, stringOverride(o.street)), areaM2: field("areaM2", l.areaM2, numberOverride(o.areaM2)), rooms: field("rooms", l.rooms, numberOverride(o.rooms)), floor: field("floor", l.floor, stringOverride(o.floor)), floorsTotal: field("floorsTotal", l.floorsTotal, stringOverride(o.floorsTotal)), buildingType: field("buildingType", l.buildingType, stringOverride(o.buildingType)), yearBuilt: field("yearBuilt", l.yearBuilt, numberOverride(o.yearBuilt)), ownership: field("ownership", l.ownership, stringOverride(o.ownership)), condition: field("condition", l.condition, stringOverride(o.condition)), monthlyFee: field("monthlyFee", l.monthlyFee, numberOverride(o.monthlyFee)), askingPrice: field("askingPrice", l.askingPrice, numberOverride(o.askingPrice)), askingPricePerM2: field("askingPricePerM2", ppm, undefined, true), source: field("source", l.source, undefined), sourceUrl: field("sourceUrl", l.sourceUrl, undefined), postId: field("postId", l.externalListingId, undefined), galleryStatus: field("galleryStatus", l.galleryStatus, undefined), imageCount: field("imageCount", l.imageCount, undefined) };
}

function verifyFacts(facts: DealFacts, identityExact: boolean, conflicts: BuildDealInput["listing"]["conflicts"]) {
  const critical: string[] = [], optional: string[] = [], confirmed: string[] = [];
  for (const name of ["askingPrice", "areaM2", "rooms", "city"] as const) (facts[name].effectiveValue == null ? critical : confirmed).push(name);
  for (const name of ["district", "street", "buildingType", "floor", "floorsTotal", "ownership", "condition", "monthlyFee"] as const) (facts[name].effectiveValue == null ? optional : confirmed).push(name);
  if (identityExact) confirmed.unshift("identity"); else critical.unshift("identity");
  const conflictCodes = conflicts.map((item) => `FACT_CONFLICT:${String(item.field)}`);
  return { result: { verificationStatus: critical.length || conflictCodes.length ? "INCOMPLETE" : "VERIFIED", verifiedFacts: confirmed, missingCriticalFields: critical, missingOptionalFields: optional, conflicts: conflictCodes } as VerifyResult, confidence: clamp(100 - critical.length * 18 - optional.length * 4 - conflictCodes.length * 30, 0, 100), warnings: [...optional.map((name) => `MISSING_OPTIONAL:${name}`), ...conflictCodes], reasons: conflictCodes.length ? ["VERIFY_FACT_CONFLICT"] : critical.length ? ["VERIFY_CRITICAL_FACTS_MISSING"] : ["VERIFY_FACTS_CONFIRMED"] };
}

function buildMarket(input: BuildDealInput, facts: DealFacts, verify: DirectorOutput<VerifyResult>, policy: InvestmentDecisionPolicy, analysisLevel: AnalysisLevel): DirectorOutput<MarketResult> {
  const started = performance.now();
  const area = positive(facts.areaM2.effectiveValue); const override = positive(input.overrides.resalePerM2);
  const selected = override === null ? input.market : { id: null, matchedBy: "DEAL_OVERRIDE", low: money(override * .95), base: override, high: money(override * 1.05), confidence: 65, provenance: "USER_ASSUMPTION" as const, compCount: 0, fallbackLevel: 0, fallbackReason: "EXPLICIT_DEAL_OVERRIDE", confidencePenalty: 0, observedAt: input.now, evidenceId: `deal:${input.dealId}:resale-override`, priceEvidenceType: "USER_ASSUMPTION" as const, comparables: [] };
  const fp = fingerprint({ area, selected, verify: verify.inputFingerprint, policy });
  if (verify.status === "BLOCKED") return output<MarketResult>("MARKET", fp, input.now, 0, null, verify.result?.conflicts ?? [], verify.warnings, ["MARKET_VERIFY_BLOCKED"], [], "BLOCKED", { analysisLevel, elapsedMs: elapsed(started) });
  if (area === null) return output<MarketResult>("MARKET", fp, input.now, 0, null, ["areaM2"], [], ["MARKET_AREA_MISSING"], [], "BLOCKED", { analysisLevel, elapsedMs: elapsed(started) });
  if (!selected) return output<MarketResult>("MARKET", fp, input.now, 0, null, ["resaleAssumption"], [], ["RESALE_ASSUMPTION_MISSING"], [], "BLOCKED", { analysisLevel, elapsedMs: elapsed(started) });
  const age = selected.observedAt && Number.isFinite(Date.parse(selected.observedAt)) ? Math.max(0, (Date.parse(input.now) - Date.parse(selected.observedAt)) / 86_400_000) : Infinity;
  const checks = [{ code: "MARKET_RANGE_ORDERED", passed: selected.low > 0 && selected.low <= selected.base && selected.base <= selected.high, detail: `${selected.low}/${selected.base}/${selected.high}` }, { code: "MARKET_EVIDENCE_IDENTIFIED", passed: Boolean(selected.evidenceId || selected.id), detail: selected.evidenceId ?? selected.id ?? "missing" }, { code: "MARKET_FALLBACK_ALLOWED", passed: selected.fallbackLevel <= policy.maximumMarketFallbackLevel, detail: `level=${selected.fallbackLevel}` }, { code: "MARKET_EVIDENCE_FRESH", passed: age <= policy.maximumMarketAgeDays, detail: `ageDays=${Number.isFinite(age) ? Math.round(age) : "unknown"}` }, { code: "MARKET_MULTI_SOURCE_STANDARD", passed: selected.matchedBy !== "RESALE_COMPS" || selected.compCount >= policy.minimumMarketComparableCount, detail: `comps=${selected.compCount};minimum=${policy.minimumMarketComparableCount}` }];
  const checked = validation("MARKET", input.now, checks.every((check) => check.passed) ? "PASS" : "FAIL", checks);
  const marketExecution: DirectorExecution = { toolsRequested: ["INTERNAL_DATABASE", "COMPARABLE_ANALYSIS"], toolsSucceeded: selected.compCount > 0 ? ["INTERNAL_DATABASE", "COMPARABLE_ANALYSIS"] : ["INTERNAL_DATABASE"], toolsFailed: selected.compCount > 0 ? [] : [{ tool: "COMPARABLE_ANALYSIS", reason: "DIRECT_COMPARABLE_SET_UNAVAILABLE" }], evidenceCount: selected.compCount || Number(Boolean(selected.evidenceId || selected.id)), conflictCount: 0, elapsedMs: elapsed(started) };
  const meta = { validation: checked, fallbackLevel: selected.fallbackLevel, fallbackReason: selected.fallbackReason, confidencePenalty: selected.confidencePenalty, freshUntil: addDays(selected.observedAt, policy.maximumMarketAgeDays), analysisLevel, execution: marketExecution, elapsedMs: elapsed(started) };
  if (checked.status !== "PASS") return output<MarketResult>("MARKET", fp, input.now, selected.confidence - selected.confidencePenalty, null, ["marketEvidence"], [selected.fallbackReason ?? "MARKET_EVIDENCE_INVALID"], checked.reasonCodes, [], "BLOCKED", meta);
  const result: MarketResult = { resalePricePerM2Low: selected.low, resalePricePerM2Base: selected.base, resalePricePerM2High: selected.high, resaleValueLow: money(area * selected.low), resaleValueBase: money(area * selected.base), resaleValueHigh: money(area * selected.high), assumptionMatchedBy: selected.matchedBy, assumptionId: selected.id, compCount: selected.compCount, fallbackLevel: selected.fallbackLevel, fallbackReason: selected.fallbackReason, confidencePenalty: selected.confidencePenalty, observedAt: selected.observedAt, evidenceId: selected.evidenceId, priceEvidenceType: selected.priceEvidenceType, comparables: selected.comparables };
  const evidence: ProvenanceEntry[] = [{ field: "resalePricePerM2", provenance: selected.provenance, classification: selected.provenance === "DERIVED" ? "ESTIMATE" : "ASSUMPTION", sourceId: selected.id, observedAt: selected.observedAt, evidenceId: selected.evidenceId, assumptionId: selected.compCount ? null : selected.id }];
  return output("MARKET", fp, input.now, selected.confidence - selected.confidencePenalty, result, [], selected.confidence - selected.confidencePenalty < 50 ? ["MARKET_CONFIDENCE_LOW"] : [], [selected.compCount ? "MARKET_RESALE_COMPS_USED" : "MARKET_ASSUMPTION_USED"], evidence, "COMPLETE", { ...meta, predictions: [{ metric: "RESALE_VALUE", value: result.resaleValueBase, unit: "PLN", confidence: clamp(selected.confidence - selected.confidencePenalty, 0, 100), predictedAt: input.now }] });
}

function toUnderwritingInput(input: BuildDealInput, facts: DealFacts, market: DirectorOutput<MarketResult>): UnderwritingInput {
  const m = market.result!;
  return { listingId: input.listing.id, source: input.listing.source, sourceUrl: input.listing.sourceUrl, lifecycleStatus: input.listing.lifecycleStatus, decisionBucket: input.listing.decisionBucket, manualDecision: input.listing.manualDecision, city: facts.city.effectiveValue, district: facts.district.effectiveValue, street: facts.street.effectiveValue, areaM2: facts.areaM2.effectiveValue, rooms: facts.rooms.effectiveValue, floor: facts.floor.effectiveValue, floorsTotal: facts.floorsTotal.effectiveValue, buildingType: facts.buildingType.effectiveValue, yearBuilt: facts.yearBuilt.effectiveValue, ownership: facts.ownership.effectiveValue, condition: facts.condition.effectiveValue, monthlyFee: facts.monthlyFee.effectiveValue, askingPrice: facts.askingPrice.effectiveValue, askingPricePerM2: facts.askingPricePerM2.effectiveValue, resalePerM2: { low: m.resalePricePerM2Low, base: m.resalePricePerM2Base, high: m.resalePricePerM2High, provenance: market.provenance[0]?.provenance ?? "MARKET_ASSUMPTION", confidence: market.confidence }, priceOverride: null, resalePerM2Override: null, renovationPerM2Override: numberOverride(input.overrides.renovationPerM2), holdingMonthsOverride: numberOverride(input.overrides.holdingMonths), additionalCostsOverride: numberOverride(input.overrides.additionalCosts), galleryAvailable: (facts.imageCount.effectiveValue ?? 0) > 0 };
}

function buildUnderwriter(input: BuildDealInput, facts: DealFacts, market: DirectorOutput<MarketResult>, verify: DirectorOutput<VerifyResult>, analysisLevel: AnalysisLevel) {
  const started = performance.now();
  const fp = fingerprint({ facts, market: market.result, settings: input.settings, overrides: input.overrides });
  if (market.status !== "COMPLETE" || market.validation.status !== "PASS" || !market.result) return output<ReturnType<typeof calculateUnderwriting>>("UNDERWRITER", fp, input.now, 0, null, market.missingFields, market.warnings, ["UNDERWRITING_MARKET_BLOCKED"], [], "BLOCKED", { analysisLevel, elapsedMs: elapsed(started) });
  const uInput = toUnderwritingInput(input, facts, market); const result = calculateUnderwriting(uInput, input.settings); const boundary = validateMaxPurchaseBoundary(uInput, input.settings, result.maxPurchasePrice); const checked = validation("UNDERWRITER", input.now, boundary.status, boundary.checks);
  const confidence = Math.round((verify.confidence + market.confidence) / 2);
  const predictions: PredictionMetric[] = [{ metric: "DURATION_DAYS", value: input.settings.holdingMonths * 30, unit: "DAYS", confidence, predictedAt: input.now }];
  if (result.renovationTotal !== null) predictions.push({ metric: "RENOVATION_COST", value: result.renovationTotal, unit: "PLN", confidence, predictedAt: input.now });
  if (result.profitBase !== null) predictions.push({ metric: "PROFIT", value: result.profitBase, unit: "PLN", confidence, predictedAt: input.now });
  return output("UNDERWRITER", fp, input.now, confidence, result, result.missingFields, result.redFlags, checked.status === "PASS" ? ["UNDERWRITING_VALIDATED"] : checked.reasonCodes, Object.entries(result.provenance).map(([field, provenance]) => ({ field, provenance, classification: provenance === "DERIVED" ? "ESTIMATE" : provenance === "UNKNOWN" ? "UNKNOWN" : "FACT", evidenceId: provenance === "DERIVED" ? `derived:${input.dealId}:${field}:${fp}` : facts[field as keyof DealFacts]?.evidenceId ?? market.result?.evidenceId ?? null })), checked.status === "PASS" ? "COMPLETE" : "BLOCKED", { validation: checked, predictions, analysisLevel, elapsedMs: elapsed(started) });
}

function buildCeo(input: BuildDealInput, facts: DealFacts, verify: DirectorOutput<VerifyResult>, market: DirectorOutput<MarketResult>, underwriting: DirectorOutput<ReturnType<typeof calculateUnderwriting>>, policy: InvestmentDecisionPolicy, analysisLevel: AnalysisLevel): DirectorOutput<CeoResult> {
  const started = performance.now();
  const fp = fingerprint({ verify: verify.inputFingerprint, market: market.inputFingerprint, underwriting: underwriting.inputFingerprint, manual: input.listing.manualDecision, policy }); const u = underwriting.result;
  const rejected = input.listing.manualDecision === "REJECTED" || u?.decision === "REJECT"; const confidence = u ? Math.min(u.confidenceScore, verify.confidence, market.confidence) : Math.min(verify.confidence, market.confidence); const gates = criticalGates(input, facts, verify, market, underwriting, policy); const gatesPass = gates.every((gate) => gate.passed);
  const raw = u?.decision ?? (rejected ? "REJECT" : "REVIEW"); const decision: CeoResult["decision"] = rejected ? "REJECT" : raw === "HOT" && !gatesPass ? "REVIEW" : raw; const action: CeoResult["action"] = decision === "REJECT" ? "ODRZUĆ" : decision === "TOO_EXPENSIVE" ? "NEGOCJUJ" : decision === "HOT" && gatesPass ? "KUP" : decision === "GOOD" ? "JEDŹ OBEJRZEĆ" : "HOLD / ZBIERZ DANE"; const opening = u?.targetPurchasePrice == null ? null : money(u.targetPurchasePrice * (1 - input.settings.targetNegotiationBufferPercent / 100)); const missing = unique([...verify.missingFields, ...market.missingFields, ...gates.filter((gate) => !gate.passed).map((gate) => gate.fact)]); const questions = informationRequests(input.dealId, gates, verify); const deepDiveRecommended = (facts.askingPrice.effectiveValue ?? 0) >= policy.deepDiveValueThresholdPLN || ["KUP", "NEGOCJUJ", "JEDŹ OBEJRZEĆ"].includes(action); const deepDiveReason = deepDiveRecommended ? `Material exposure or action threshold reached; rerun VERIFY, MARKET, RISK and UNDERWRITER at level 2 before commitment.` : null;
  const result: CeoResult = { decision, action, headline: rejected ? "Twarde wykluczenie zamyka ofertę" : action === "KUP" ? "Mocny deal po pełnej walidacji" : decision === "TOO_EXPENSIVE" ? "Ekonomia wymaga niższej ceny" : "Decyzja wymaga potwierdzenia danych", openingOffer: opening, targetPurchasePrice: u?.targetPurchasePrice ?? null, maxPurchasePrice: u?.maxPurchasePrice ?? null, expectedProfitBase: u?.profitBase ?? null, expectedProfitConservative: u?.profitLow ?? null, flipScore: u?.flipScore ?? 0, confidence, strengths: u?.strengths ?? [], risks: unique([...(u?.redFlags ?? []), ...verify.warnings, ...market.warnings]), missingBeforeViewing: verify.result?.missingCriticalFields ?? [], missingBeforePurchase: missing, recommendation: action, investmentThesis: u?.profitBase == null ? "Ekonomia nie została wiarygodnie policzona." : `Bazowy zysk ${money(u.profitBase)} PLN jest ważny tylko przy spełnieniu wszystkich bramek.`, bearCase: scenarioText("Bear", u?.scenarios.conservative.resaleValue ?? null, u?.profitLow ?? null), baseCase: scenarioText("Base", u?.scenarios.base.resaleValue ?? null, u?.profitBase ?? null), bullCase: scenarioText("Bull", u?.scenarios.optimistic.resaleValue ?? null, u?.profitHigh ?? null), dissent: dissent(u, verify, market, gates), conditionsToProceed: unique([...(u?.maxPurchasePrice == null ? [] : [`Cena zakupu <= ${money(u.maxPurchasePrice)} PLN`]), ...gates.filter((gate) => !gate.passed).map((gate) => gate.reason)]), walkAwayConditions: unique([u?.maxPurchasePrice == null ? "Brak zwalidowanej ceny maksymalnej" : `Cena > ${money(u.maxPurchasePrice)} PLN`, "Potwierdzona wada prawna", "Nierozwiązany konflikt materialnych faktów"]), nextBestAction: action === "NEGOCJUJ" ? `Oferta otwierająca: ${opening ?? "warunkowa"}.` : action === "JEDŹ OBEJRZEĆ" || action === "KUP" ? "Zweryfikuj dokumenty; zakup wymaga decyzji człowieka." : action === "ODRZUĆ" ? "Nie reaktywuj automatycznie." : questions[0]?.question ?? "Uzupełnij pierwszą niespełnioną bramkę.", redTeam: redTeam(u, verify, market), criticalGates: gates, humanApprovalRequired: true, autonomousPurchaseAllowed: false, nextBestQuestions: questions.slice(0, 3), deepDiveRecommended, deepDiveReason, directorTrackRecords: input.directorTrackRecords ?? [] };
  const checks = [{ code: "CEO_DEPENDENCIES_VALIDATED", passed: rejected || (verify.validation.status === "PASS" && market.validation.status === "PASS" && underwriting.validation.status === "PASS"), detail: `${verify.validation.status}/${market.validation.status}/${underwriting.validation.status}` }, { code: "CEO_BUY_REQUIRES_ALL_GATES", passed: action !== "KUP" || gatesPass, detail: gates.filter((gate) => !gate.passed).map((gate) => gate.fact).join(",") || "pass" }, { code: "CEO_BUY_REQUIRES_CONFIDENCE", passed: action !== "KUP" || confidence >= policy.minimumBuyConfidence, detail: `${confidence}/${policy.minimumBuyConfidence}` }, { code: "CEO_HUMAN_AUTHORITY", passed: result.humanApprovalRequired && !result.autonomousPurchaseAllowed, detail: "No autonomous purchase." }]; const checked = validation("CEO", input.now, checks.every((check) => check.passed) ? "PASS" : "FAIL", checks);
  return output("CEO", fp, input.now, confidence, result, missing, result.risks, [rejected ? "CEO_HARD_REJECT" : action === "KUP" ? "CEO_BUY_GATES_PASS" : "CEO_HOLD_OR_CONDITIONAL"], uniqueProvenance([...verify.provenance, ...market.provenance, ...underwriting.provenance]), checked.status === "PASS" ? "COMPLETE" : "BLOCKED", { validation: checked, vetoes: rejected ? [{ code: "HARD_REJECT_VETO", source: "VERIFY", reason: "Score cannot override a manual or hard reject." }] : [], informationRequests: questions.slice(0, 3), analysisLevel, elapsedMs: elapsed(started) });
}

function criticalGates(input: BuildDealInput, facts: DealFacts, verify: DirectorOutput<VerifyResult>, market: DirectorOutput<MarketResult>, underwriting: ReturnType<typeof buildUnderwriter>, policy: InvestmentDecisionPolicy): CeoResult["criticalGates"] {
  const marketCrossChecked = Boolean(market.result && (market.result.compCount >= policy.minimumMarketComparableCount || market.result.priceEvidenceType === "TRANSACTION" || market.result.priceEvidenceType === "MIXED"));
  const known: Record<InvestmentDecisionPolicy["criticalBuyFacts"][number], boolean> = { identity: input.listing.identityExact, askingPrice: positive(facts.askingPrice.effectiveValue) !== null, areaM2: positive(facts.areaM2.effectiveValue) !== null, city: Boolean(facts.city.effectiveValue), ownership: Boolean(facts.ownership.effectiveValue), legalStatus: false, marketEvidence: market.status === "COMPLETE" && market.validation.status === "PASS" && marketCrossChecked, renovationScope: Boolean(facts.condition.effectiveValue), economics: Boolean(underwriting.result && underwriting.validation.status === "PASS"), riskReview: verify.result?.conflicts.length === 0 };
  return policy.criticalBuyFacts.map((fact) => ({ fact, passed: known[fact], reason: known[fact] ? `${fact}: confirmed` : `${fact}: requires evidence` }));
}

function selectAnalysisLevel(input: BuildDealInput, policy: InvestmentDecisionPolicy): AnalysisLevel {
  if (input.requestedAnalysisLevel !== undefined) return input.requestedAnalysisLevel;
  if (input.listing.manualDecision === "REJECTED" || input.listing.decisionBucket === "REJECTED") return 0;
  return (input.listing.askingPrice ?? 0) >= policy.deepDiveValueThresholdPLN ? 2 : 1;
}

function informationRequests(dealId: string, gates: CeoResult["criticalGates"], verify: DirectorOutput<VerifyResult>): InformationRequest[] {
  const scores: Record<string, { score: number; priority: InformationRequest["priority"]; impact: InformationRequest["decisionImpact"]; evidence: string }> = {
    legalStatus: { score: 100, priority: "CRITICAL", impact: ["REJECT", "BUY"], evidence: "Primary legal document or qualified legal review" },
    ownership: { score: 95, priority: "CRITICAL", impact: ["REJECT", "HOLD", "BUY"], evidence: "Title document / land and mortgage register" },
    askingPrice: { score: 90, priority: "CRITICAL", impact: ["NEGOTIATE", "BUY"], evidence: "Current seller asking price" },
    marketEvidence: { score: 85, priority: "HIGH", impact: ["HOLD", "NEGOTIATE", "BUY"], evidence: "At least three current high-quality comparables or stronger evidence" },
    areaM2: { score: 85, priority: "HIGH", impact: ["REJECT", "NEGOTIATE", "BUY"], evidence: "Primary document or exact verified listing fact" },
    renovationScope: { score: 80, priority: "HIGH", impact: ["HOLD", "NEGOTIATE", "BUY"], evidence: "Inspection scope and/or contractor estimate" },
    city: { score: 75, priority: "HIGH", impact: ["REJECT", "HOLD"], evidence: "Exact canonical listing location" },
    identity: { score: 100, priority: "CRITICAL", impact: ["REJECT", "HOLD"], evidence: "Exact canonical source binding" },
    economics: { score: 90, priority: "CRITICAL", impact: ["REJECT", "NEGOTIATE", "BUY"], evidence: "Independently validated deterministic calculation" },
    riskReview: { score: 90, priority: "CRITICAL", impact: ["REJECT", "HOLD", "BUY"], evidence: "Resolved material conflicts and risk review" },
  };
  const fields = unique([...gates.filter((gate) => !gate.passed).map((gate) => gate.fact), ...(verify.result?.missingCriticalFields ?? []), ...(verify.result?.missingOptionalFields ?? [])]);
  return fields.map((field): InformationRequest => { const spec = scores[field] ?? { score: 35, priority: "MEDIUM" as const, impact: ["HOLD"] as InformationRequest["decisionImpact"], evidence: "Reliable identified source" }; const requestedBy: InformationRequest["requestedBy"] = field === "legalStatus" || field === "ownership" ? "LEGAL" : field === "marketEvidence" ? "MARKET" : "VERIFY"; return { id: `voi:${dealId}:${field}`, field, question: nextQuestion(field), priority: spec.priority, valueOfInformation: spec.score, decisionImpact: spec.impact, requestedBy, evidenceNeeded: spec.evidence, status: "OPEN" }; }).sort((left, right) => right.valueOfInformation - left.valueOfInformation);
}

function nextQuestion(field: string): string {
  const questions: Record<string, string> = { legalStatus: "Czy dostępny jest numer KW i dokument potwierdzający brak obciążeń?", ownership: "Jaka jest forma własności i jaki dokument ją potwierdza?", askingPrice: "Jaka jest aktualna cena i realny zakres negocjacji?", marketEvidence: "Czy mamy co najmniej trzy aktualne, porównywalne oferty lub dane transakcyjne?", areaM2: "Jaki metraż wynika z dokumentu, a nie tylko z opisu?", renovationScope: "Jaki zakres remontu potwierdziły oględziny lub kosztorys?", identity: "Jaki kanoniczny identyfikator potwierdza tę ofertę?", economics: "Czy wszystkie progi finansowe przeszły niezależną walidację?", riskReview: "Który konflikt lub materialne ryzyko pozostaje nierozwiązane?", city: "Jaki dokładny adres potwierdza lokalizację?" };
  return questions[field] ?? `Jakie wiarygodne źródło potwierdza ${field}?`;
}

function buildEvidenceFabric(input: BuildDealInput, facts: DealFacts, market: DirectorOutput<MarketResult>, underwriting: DirectorOutput<ReturnType<typeof calculateUnderwriting>>): EvidenceItem[] {
  const conflicts = new Map<string, string[]>();
  for (const conflict of input.listing.conflicts) for (const value of conflict.values) conflicts.set(value.evidenceId, conflict.values.filter((other) => other.evidenceId !== value.evidenceId).map((other) => other.evidenceId));
  const items: EvidenceItem[] = Object.entries(facts).flatMap(([field, fact]) => fact.effectiveValue === null || !fact.evidenceId ? [] : [{ id: fact.evidenceId, dealId: input.dealId, type: fact.classification, sourceType: fact.classification === "USER_OVERRIDE" ? "USER_PROVIDED" : fact.classification === "ESTIMATE" ? "VERIFIED_STRUCTURED_DATA" : "DIRECT_OBSERVATION", sourceName: fact.source, value: fact.effectiveValue, sourceUrl: input.listing.sourceUrl, documentId: null, observedAt: fact.observedAt, validFrom: fact.observedAt, validUntil: null, reliability: fact.confidence, confidence: fact.confidence, directorWhoRequested: field === "askingPricePerM2" ? "UNDERWRITER" : "VERIFY", verificationStatus: conflicts.has(fact.evidenceId) ? "CONFLICT" : "VERIFIED", conflictsWith: conflicts.get(fact.evidenceId) ?? [] } satisfies EvidenceItem]);
  for (const conflict of input.listing.conflicts) for (const candidate of conflict.values) if (!items.some((item) => item.id === candidate.evidenceId)) items.push({ id: candidate.evidenceId, dealId: input.dealId, type: "FACT", sourceType: "DIRECT_OBSERVATION", sourceName: candidate.source, value: candidate.value, sourceUrl: input.listing.sourceUrl, documentId: null, observedAt: candidate.observedAt, validFrom: candidate.observedAt, validUntil: null, reliability: 70, confidence: 70, directorWhoRequested: "VERIFY", verificationStatus: "CONFLICT", conflictsWith: conflict.values.filter((other) => other.evidenceId !== candidate.evidenceId).map((other) => other.evidenceId) });
  if (market.result?.evidenceId) items.push({ id: market.result.evidenceId, dealId: input.dealId, type: market.result.priceEvidenceType === "USER_ASSUMPTION" ? "ASSUMPTION" : "ESTIMATE", sourceType: market.result.compCount >= 3 ? "MULTIPLE_INDEPENDENT_SOURCES" : market.result.priceEvidenceType === "USER_ASSUMPTION" ? "USER_PROVIDED" : "REPUTABLE_SECONDARY", sourceName: market.result.assumptionMatchedBy, value: { low: market.result.resalePricePerM2Low, base: market.result.resalePricePerM2Base, high: market.result.resalePricePerM2High, comparables: market.result.comparables.map((comp) => comp.id) }, sourceUrl: null, documentId: null, observedAt: market.result.observedAt, validFrom: market.result.observedAt, validUntil: market.freshUntil, reliability: market.confidence, confidence: market.confidence, directorWhoRequested: "MARKET", verificationStatus: market.validation.status === "PASS" ? "VERIFIED" : "UNVERIFIED", conflictsWith: [] });
  for (const prediction of underwriting.predictions) items.push({ id: `prediction:${input.dealId}:${prediction.metric}:${underwriting.inputFingerprint}`, dealId: input.dealId, type: "PREDICTION", sourceType: "VERIFIED_STRUCTURED_DATA", sourceName: "DETERMINISTIC_UNDERWRITER", value: prediction, sourceUrl: null, documentId: null, observedAt: prediction.predictedAt, validFrom: prediction.predictedAt, validUntil: null, reliability: prediction.confidence, confidence: prediction.confidence, directorWhoRequested: "UNDERWRITER", verificationStatus: underwriting.validation.status === "PASS" ? "VERIFIED" : "UNVERIFIED", conflictsWith: [] });
  const underwritingValues = underwriting.result as unknown as Record<string, unknown> | null;
  for (const evidence of underwriting.provenance) if (evidence.evidenceId?.startsWith("derived:") && !items.some((item) => item.id === evidence.evidenceId)) items.push({ id: evidence.evidenceId, dealId: input.dealId, type: "ESTIMATE", sourceType: "VERIFIED_STRUCTURED_DATA", sourceName: "DETERMINISTIC_UNDERWRITER", value: underwritingValues?.[evidence.field] ?? { field: evidence.field }, sourceUrl: null, documentId: null, observedAt: underwriting.computedAt, validFrom: underwriting.computedAt, validUntil: null, reliability: underwriting.confidence, confidence: underwriting.confidence, directorWhoRequested: "UNDERWRITER", verificationStatus: underwriting.validation.status === "PASS" ? "VERIFIED" : "UNVERIFIED", conflictsWith: [] });
  return [...new Map(items.map((item) => [item.id, item])).values()];
}

function redTeam(u: ReturnType<typeof calculateUnderwriting> | null, verify: DirectorOutput<VerifyResult>, market: DirectorOutput<MarketResult>): CeoResult["redTeam"] { return [{ risk: "RESALE_DOWNSIDE", finding: (u?.profitLow ?? 0) < 0 ? "Bear case is loss-making." : "Bear-case profit must survive.", severity: (u?.profitLow ?? 0) < 0 ? "HIGH" : "MEDIUM" }, { risk: "RENOVATION_OVERRUN", finding: "Scope and overrun require site evidence.", severity: "MEDIUM" }, { risk: "HOLDING_DELAY", finding: "Delay increases holding and finance cost.", severity: "MEDIUM" }, { risk: "LIQUIDITY", finding: "Exit liquidity is an estimate.", severity: market.confidence < 70 ? "HIGH" : "MEDIUM" }, { risk: "LEGAL", finding: "Title and encumbrances require documents.", severity: "HIGH" }, { risk: "MISSING_DATA", finding: verify.missingFields.join(",") || "No verifier omissions.", severity: verify.missingFields.length ? "HIGH" : "LOW" }, { risk: "SENSITIVITY", finding: "Resale, renovation, time and purchase price can change the decision.", severity: "MEDIUM" }]; }
function dissent(u: ReturnType<typeof calculateUnderwriting> | null, verify: DirectorOutput<VerifyResult>, market: DirectorOutput<MarketResult>, gates: CeoResult["criticalGates"]): string[] { const values: string[] = []; if ((u?.flipScore ?? 0) >= 70 && Math.min(verify.confidence, market.confidence) < 70) values.push("High score rests on low-confidence evidence."); if ((u?.profitLow ?? 0) < 0 && (u?.profitBase ?? 0) > 0) values.push("Bear case loses money."); if (gates.some((gate) => !gate.passed)) values.push("Critical purchase gates remain unverified."); return values; }

type OutputMeta = Partial<Pick<DirectorOutput<unknown>, "validation" | "fallbackLevel" | "fallbackReason" | "confidencePenalty" | "freshUntil" | "vetoes" | "predictions" | "execution" | "informationRequests">> & { analysisLevel?: AnalysisLevel; elapsedMs?: number };
function output<T>(director: DirectorOutput<T>["director"], fp: string, at: string, confidence: number, result: T | null, missingFields: string[], warnings: string[], reasonCodes: string[], provenance: ProvenanceEntry[], status: DirectorOutput<T>["status"] = "COMPLETE", meta: OutputMeta = {}): DirectorOutput<T> {
  const missing = unique(missingFields), risks = unique(warnings), reasons = unique(reasonCodes); const checked = meta.validation ?? validation(director, at, status === "BLOCKED" ? "BLOCKED" : "PASS", [{ code: `${director}_OUTPUT_STRUCTURED`, passed: result !== null, detail: result === null ? "No result." : "Structured result present." }]); const toolPolicy = policyFor(director, meta.analysisLevel ?? 1); const requiredTools = toolPolicy.filter((step) => step.required).map((step) => step.tool); const execution = meta.execution ?? { toolsRequested: requiredTools, toolsSucceeded: status === "COMPLETE" ? requiredTools : [], toolsFailed: status === "BLOCKED" ? requiredTools.map((tool) => ({ tool, reason: reasons[0] ?? "REQUIRED_EVIDENCE_UNAVAILABLE" })) : [], evidenceCount: provenance.filter((item) => item.evidenceId || item.assumptionId || item.sourceId).length, conflictCount: reasons.filter((reason) => reason.includes("CONFLICT")).length, elapsedMs: meta.elapsedMs ?? 0 };
  return { director, status, version: 3, inputFingerprint: fp, computedAt: at, confidence: clamp(confidence, 0, 100), result, missingFields: missing, warnings: risks, reasonCodes: reasons, provenance, finding: status === "BLOCKED" ? `${director} blocked by evidence or validation.` : `${director} completed with confidence ${Math.round(confidence)}.`, recommendation: status === "BLOCKED" ? `Verify ${missing.join(", ") || "blocked input"}.` : director === "CEO" ? "Execute only the conditional human-approved action." : "Pass only validated output downstream.", evidence: provenance.map((item) => `${item.field}:${item.classification ?? item.provenance}:${item.evidenceId ?? item.assumptionId ?? item.sourceId ?? "unidentified"}`), risks, missingData: missing, nextBestActions: missing.length ? missing.map((name) => `Confirm ${name}`) : ["Revalidate after material change"], decisionTriggers: reasons, whatWouldChangeMyMind: missing.length ? missing.map((name) => `Identified evidence for ${name}`) : ["Material fact, assumption or freshness change"], validation: checked, fallbackLevel: meta.fallbackLevel ?? 0, fallbackReason: meta.fallbackReason ?? null, confidencePenalty: meta.confidencePenalty ?? 0, freshUntil: meta.freshUntil ?? null, vetoes: meta.vetoes ?? [], predictions: meta.predictions ?? [], toolPolicy, execution, informationRequests: meta.informationRequests ?? [], asOf: at };
}
function validation(scope: string, at: string, status: ValidationResult["status"], checks: ValidationResult["checks"]): ValidationResult { return { status, validator: "INDEPENDENT_RULE_VALIDATOR", version: 1, inputFingerprint: fingerprint({ scope, checks }), checkedAt: at, checks, reasonCodes: checks.filter((check) => !check.passed).map((check) => check.code) }; }
function buildPlaybook(facts: DealFacts, ceo: DirectorOutput<CeoResult>): DealPlaybook { const before = ceo.result?.missingBeforeViewing ?? [], purchase = ceo.result?.missingBeforePurchase ?? []; return { beforeCall: ["Open canonical listing and price history", ...before.map((name) => `Ask about ${name}`)], sellerQuestions: ["What is the legal title and are there encumbrances?", "Why is it being sold?", "Is price negotiable?", ...(facts.monthlyFee.effectiveValue == null ? ["What is the monthly fee?"] : [])], viewingChecklist: ["Confirm area and layout", "Inspect installations and moisture", "Record renovation scope", ...before.map((name) => `Verify ${name}`)], negotiationPlan: [ceo.result?.openingOffer == null ? "Conditional offer only" : `Opening: ${money(ceo.result.openingOffer)} PLN`, ceo.result?.targetPurchasePrice == null ? "Target after validation" : `Target: ${money(ceo.result.targetPurchasePrice)} PLN`, ceo.result?.maxPurchasePrice == null ? "No maximum without validation" : `Never exceed: ${money(ceo.result.maxPurchasePrice)} PLN`], documentsRequired: ["Title document", "No-arrears certificate", "Unit plan", "Community/cooperative documents"], conditionsBeforePurchase: unique([...purchase.map((name) => `Confirm ${name}`), ...(ceo.result?.conditionsToProceed ?? []), "Human approval is mandatory"]) }; }
function scenarioText(label: string, resale: number | null, profit: number | null): string { return `${label}: resale ${resale ?? "unknown"}, profit ${profit ?? "unknown"}.`; }
function factProvenance(facts: DealFacts): ProvenanceEntry[] { return Object.entries(facts).map(([field, value]) => ({ field, provenance: value.provenance, classification: value.classification, sourceId: value.source, observedAt: value.observedAt, evidenceId: value.evidenceId, assumptionId: value.assumptionId })); }
function addDays(value: string | null, days: number): string | null { return value && Number.isFinite(Date.parse(value)) ? new Date(Date.parse(value) + days * 86_400_000).toISOString() : null; }
function unique(values: string[]): string[] { return [...new Set(values.filter(Boolean))]; }
function uniqueProvenance(values: ProvenanceEntry[]): ProvenanceEntry[] { return [...new Map(values.map((item) => [`${item.field}:${item.evidenceId ?? item.assumptionId ?? item.sourceId ?? item.provenance}`, item])).values()]; }
function elapsed(started: number): number { return Math.max(0, Math.ceil(performance.now() - started)); }
function stringOverride(value: unknown): string | null | undefined { return value === undefined ? undefined : typeof value === "string" && value.trim() ? value.trim() : null; }
function numberOverride(value: unknown): number | null | undefined { return value === undefined ? undefined : typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : null; }
function positive(value: number | null | undefined): number | null { return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : null; }
function money(value: number): number { return Math.round(value * 100) / 100; }
function clamp(value: number, min: number, max: number): number { return Math.max(min, Math.min(max, Number.isFinite(value) ? value : min)); }
export function fingerprint(value: unknown): string { const text = stable(value); let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return `v1-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
function stable(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stable(item)}`).join(",")}}`; }
