"use client";

import Image from "next/image";
import { STYLE_CONFIGS } from "../prompts";
import { RENOVATION_STYLES, type RenovationStyle } from "../types";

export function StyleSelector({ imageUrl, value, onChange }: { imageUrl: string; value: RenovationStyle; onChange: (style: RenovationStyle) => void }) {
  return <div className="-mx-4 flex snap-x snap-mandatory gap-3 overflow-x-auto px-4 pb-3 sm:mx-0 sm:grid sm:grid-cols-3 sm:overflow-visible sm:px-0 xl:grid-cols-4 2xl:grid-cols-8">{RENOVATION_STYLES.map((style) => { const item = STYLE_CONFIGS[style]; const active = style === value; return <button aria-pressed={active} className={`group w-56 shrink-0 snap-start overflow-hidden rounded-2xl border text-left outline-none transition-all duration-300 focus-visible:ring-2 focus-visible:ring-gold sm:w-auto sm:shrink ${active ? "border-gold/70 bg-gold/[0.10] shadow-lg shadow-gold/10" : "border-white/10 bg-white/[0.035] active:border-gold/30 sm:hover:-translate-y-1 sm:hover:border-gold/30 sm:hover:shadow-xl sm:hover:shadow-black/20"}`} key={style} onClick={() => onChange(style)} type="button"><div className="relative aspect-[4/3] overflow-hidden bg-muted"><Image alt={`Styl ${item.label}`} className="object-cover transition-transform duration-500 group-hover:scale-105" fill sizes="224px" src={imageUrl} unoptimized /><div className={`absolute inset-0 bg-gradient-to-br ${item.tint} mix-blend-multiply`} /><div className="absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-black/80 to-transparent" />{item.recommended ? <span className="absolute left-2 top-2 rounded-full border border-gold/40 bg-black/70 px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-gold backdrop-blur">⭐ Polecany</span> : null}</div><div className="p-3"><p className="text-sm font-bold">{item.label}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{item.description}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-gold">{item.cost}</p></div></button>; })}</div>;
}
