import assert from "node:assert/strict";
import test from "node:test";
import { createAlertsForListing, type AlertListing } from "./alert-rules.ts";

const listing:AlertListing={id:"listing-1",title:"Okazja",description:null,source:"facebook",price:250000,area:50,pricePerSqm:5000,city:"Łódź",district:"Bałuty",originalUrl:"https://facebook.com/post",flipScore:90,createdAt:"2026-08-09T12:00:00Z",firstSeenAt:"2026-08-09T12:05:00Z",sellerType:"private",condition:"renovation",opportunityScore:88,neighborhood:"Teofilów",facebookUrl:"https://facebook.com/post",groupName:null,groupPriority:null,flags:[]};
test("creates all score, private and recent Facebook alerts",()=>{const alerts=createAlertsForListing(listing,[],Date.parse("2026-08-09T12:10:00Z"));assert.deepEqual(new Set(alerts.map(a=>a.type)),new Set(["facebook_opportunity","high_flip_score","private_seller","new_listing"]));});
test("creates a price-drop alert only for a real decrease",()=>{const alerts=createAlertsForListing(listing,[{price:240000,capturedAt:"2026-08-09T13:00:00Z"},{price:250000,capturedAt:"2026-08-09T12:00:00Z"}],Date.parse("2026-08-10"));assert.equal(alerts.filter(a=>a.type==="price_drop").length,1);});
test("event ids are deterministic and prevent duplicates",()=>{const first=createAlertsForListing(listing,[],Date.parse("2026-08-09T12:10:00Z"));const second=createAlertsForListing(listing,[],Date.parse("2026-08-09T12:10:00Z"));assert.deepEqual(first.map(a=>a.id),second.map(a=>a.id));assert.equal(new Set(first.map(a=>a.eventKey)).size,first.length);});
test("does not create recent-listing alert after fifteen minutes",()=>{const alerts=createAlertsForListing(listing,[],Date.parse("2026-08-09T12:21:00Z"));assert.equal(alerts.some(a=>a.type==="new_listing"),false);});
test("creates Facebook opportunity from investor keyword without changing score",()=>{const alerts=createAlertsForListing({...listing,opportunityScore:40,flipScore:40,sellerType:null,condition:null,description:"Sprzedaż bez pośredników, lokal do remontu",flags:[]},[],Date.parse("2026-08-10"));assert.equal(alerts.some(alert=>alert.type==="facebook_opportunity"),true);});
test("price drop event version is the new price",()=>{const alert=createAlertsForListing(listing,[{price:240000,capturedAt:"2026-08-09T13:00:00Z"},{price:250000,capturedAt:"2026-08-09T12:00:00Z"}],Date.parse("2026-08-10")).find(item=>item.type==="price_drop");assert.equal(alert?.eventKey,"listing-1:price_drop:240000");});
