import "server-only";
import { createFacebookWatcherAdminClient } from "@/features/facebook-watcher/supabase-admin";
import { listWatchedFacebookGroups } from "@/features/facebook-groups/server";
import { createAlertsForListing, type AlertListing, type PricePoint } from "./alert-rules";
import type { InvestmentAlert } from "./types";

type Row=Record<string,unknown>;
const memoryReadState:Map<string,string>=(globalThis as typeof globalThis&{__flipAlertsRead?:Map<string,string>}).__flipAlertsRead??new Map();
(globalThis as typeof globalThis&{__flipAlertsRead?:Map<string,string>}).__flipAlertsRead=memoryReadState;

export async function getAlerts():Promise<InvestmentAlert[]>{
  const supabase=createFacebookWatcherAdminClient(); const groups=await listWatchedFacebookGroups(); const priorities=new Map(groups.map(group=>[normalize(group.name),group.priority]));
  const [listingsResult,metadataResult,snapshotsResult]=await Promise.all([
    supabase.from("listings").select("id,title,description,source,price,area,price_per_sqm,city,district,original_url,flip_score,created_at,first_seen_at").eq("status","active").order("created_at",{ascending:false}).limit(500),
    supabase.from("listing_source_metadata").select("listing_id,source_post_url,group_name,collected_at,metadata").eq("source","facebook"),
    supabase.from("listing_snapshots").select("listing_id,price,captured_at").order("captured_at",{ascending:false}).limit(2000),
  ]);
  if(listingsResult.error)throw new Error(`Nie udało się pobrać danych alertów: ${listingsResult.error.message}`);
  const metadata=new Map<string,Row>(); for(const row of metadataResult.data??[]){if(typeof row.listing_id==="string"&&!metadata.has(row.listing_id))metadata.set(row.listing_id,{...asRecord(row.metadata),source_post_url:row.source_post_url,group_name:row.group_name,collected_at:row.collected_at});}
  const snapshots=new Map<string,PricePoint[]>(); for(const row of snapshotsResult.data??[]){if(typeof row.listing_id!=="string"||typeof row.captured_at!=="string")continue;const values=snapshots.get(row.listing_id)??[];values.push({price:num(row.price),capturedAt:row.captured_at});snapshots.set(row.listing_id,values);}
  const generated=(listingsResult.data??[]).flatMap(row=>{const meta=metadata.get(String(row.id))??{};const flags=Array.isArray(meta.flags)?meta.flags.filter((value):value is string=>typeof value==="string"):[];const groupName=str(meta.group_name);const listing:AlertListing={id:String(row.id),title:str(row.title)??"Oferta bez tytułu",description:str(row.description),source:String(row.source),price:num(row.price),area:num(row.area),pricePerSqm:num(row.price_per_sqm),city:str(row.city),district:str(row.district),originalUrl:str(row.original_url),flipScore:num(row.flip_score),createdAt:str(row.created_at)??new Date(0).toISOString(),firstSeenAt:str(meta.firstImportedAt)??str(row.first_seen_at)??str(row.created_at)??new Date(0).toISOString(),sellerType:str(meta.sellerType)??(flags.some(flag=>/bezpośred|właściciel/i.test(flag))?"private":null),condition:str(meta.condition)??(flags.some(flag=>/remont/i.test(flag))?"renovation":null),opportunityScore:num(meta.opportunityScore),neighborhood:str(meta.neighborhood),facebookUrl:str(meta.source_post_url),groupName,groupPriority:groupName?priorities.get(normalize(groupName))??null:null,flags};return createAlertsForListing(listing,snapshots.get(listing.id)??[]);});
  const unique=[...new Map(generated.map(alert=>[alert.eventKey,alert])).values()]; return persistOrOverlay(supabase,unique);
}

export async function markAlertRead(id:string):Promise<void>{const now=new Date().toISOString();const supabase=createFacebookWatcherAdminClient();if(id==="all"){const result=await supabase.from("alerts").update({read_at:now}).is("read_at",null);if(!result.error)return;for(const alert of await getAlerts())memoryReadState.set(alert.id,now);return;}const result=await supabase.from("alerts").update({read_at:now}).eq("id",id);if(result.error)memoryReadState.set(id,now);}

async function persistOrOverlay(supabase:ReturnType<typeof createFacebookWatcherAdminClient>,alerts:InvestmentAlert[]):Promise<InvestmentAlert[]>{if(!alerts.length)return[];const rows=alerts.map(alert=>({id:alert.id,event_key:alert.eventKey,type:alert.type,listing_id:alert.listingId,title:alert.title,source:alert.source,seller_type:alert.sellerType,price:alert.price,area:alert.area,neighborhood:alert.neighborhood,city:alert.city,price_per_sqm:alert.pricePerSqm,flip_score:alert.flipScore,opportunity_score:alert.opportunityScore,condition:alert.condition,group_name:alert.groupName,flags:alert.flags,detected_at:alert.detectedAt,details_url:alert.detailsUrl,original_url:alert.originalUrl}));const saved=await supabase.from("alerts").upsert(rows,{onConflict:"event_key",ignoreDuplicates:true});if(!saved.error){const result=await supabase.from("alerts").select("*").order("detected_at",{ascending:false}).limit(200);if(!result.error)return(result.data??[]).map(fromRow);}else if(process.env.NODE_ENV==="development"&&!/does not exist|schema cache/i.test(saved.error.message))console.error("ALERT STORAGE FALLBACK",{message:saved.error.message});return alerts.map(alert=>({...alert,readAt:memoryReadState.get(alert.id)??null})).sort((a,b)=>Date.parse(b.detectedAt)-Date.parse(a.detectedAt)).slice(0,200);}
function fromRow(row:Row):InvestmentAlert{return{id:String(row.id),eventKey:String(row.event_key),type:row.type as InvestmentAlert["type"],listingId:String(row.listing_id),title:String(row.title),source:String(row.source),sellerType:str(row.seller_type),price:num(row.price),area:num(row.area),neighborhood:str(row.neighborhood),city:str(row.city),pricePerSqm:num(row.price_per_sqm),flipScore:num(row.flip_score),opportunityScore:num(row.opportunity_score),condition:str(row.condition),groupName:str(row.group_name),flags:Array.isArray(row.flags)?row.flags.filter((item):item is string=>typeof item==="string"):[],detectedAt:String(row.detected_at),readAt:str(row.read_at),detailsUrl:String(row.details_url),originalUrl:str(row.original_url)}}
function asRecord(value:unknown):Row{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Row:{}} function str(value:unknown){return typeof value==="string"&&value.trim()?value:null} function num(value:unknown){return typeof value==="number"?value:typeof value==="string"&&value!==""?Number(value):null} function normalize(value:string){return value.normalize("NFC").trim().toLocaleLowerCase("pl-PL")}
