"use client";
import { useEffect, useState } from "react";
import { Bell, BellOff, Send } from "lucide-react";
import { Button } from "@/components/ui/button";

type State = "checking" | "unsupported" | "disabled" | "enabled" | "denied";
export function PushSettings() { const [state, setState] = useState<State>("checking"); const [message, setMessage] = useState<string | null>(null); const supported = () => "serviceWorker" in navigator && "PushManager" in window && "Notification" in window;
  useEffect(() => { let active=true;void Promise.resolve().then(async()=>{if(!supported())return "unsupported" as const;const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();return subscription?"enabled" as const:Notification.permission==="denied"?"denied" as const:"disabled" as const;}).then(next=>{if(active)setState(next)});return()=>{active=false}; }, []);
  const enable = async () => { setMessage(null); try { if (!supported()) return setState("unsupported"); const permission = await Notification.requestPermission(); if (permission !== "granted") return setState("denied"); const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (!publicKey) throw new Error("Brak publicznego klucza VAPID w konfiguracji aplikacji."); const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: decode(publicKey) }); const response = await fetch("/api/push/subscribe", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setState("enabled"); setMessage(body.persisted ? "Subskrypcja zapisana." : "Subskrypcja działa w trybie testowym; zastosuj migrację dla trwałego zapisu."); } catch (error) { setMessage(error instanceof Error ? error.message : "Nie udało się włączyć powiadomień."); } };
  const disable = async () => { const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.getSubscription(); if (subscription) { await fetch("/api/push/unsubscribe", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ endpoint: subscription.endpoint }) }); await subscription.unsubscribe(); } setState("disabled"); setMessage("Powiadomienia wyłączone na tym urządzeniu."); };
  const test = async () => { setMessage(null); const response = await fetch("/api/push/test", { method: "POST" }); const body = await response.json(); setMessage(response.ok ? `Wysłano: ${body.sent}/${body.attempted}.` : body.error); };
  return <section className="ui-section"><div className="flex items-center gap-3">{state === "enabled" ? <Bell className="text-gold"/> : <BellOff className="text-muted-foreground"/>}<div><h2 className="text-xl font-bold">Powiadomienia o okazjach</h2><p className="text-sm text-muted-foreground">{label(state)}</p></div></div>{state === "unsupported" ? <p className="mt-4 rounded-xl border border-warning/30 p-3 text-sm text-warning">Ta przeglądarka nie obsługuje Service Worker, Push API lub Notification API. Na iOS zainstaluj aplikację na ekranie głównym i uruchom ją jako PWA.</p> : null}<div className="mt-4 flex flex-wrap gap-3">{state === "enabled" ? <Button variant="outline" onClick={() => void disable()}>Wyłącz powiadomienia</Button> : <Button disabled={state === "unsupported" || state === "denied"} onClick={() => void enable()}>Włącz powiadomienia na tym urządzeniu</Button>}<Button variant="outline" disabled={state !== "enabled"} onClick={() => void test()}><Send className="size-4"/>Wyślij testowe powiadomienie</Button></div>{message ? <p className="mt-3 text-sm text-muted-foreground">{message}</p> : null}</section>;
}
function label(state: State) { if (state === "enabled") return "🔔 Powiadomienia włączone"; if (state === "checking") return "Sprawdzam status…"; if (state === "denied") return "🔕 Uprawnienie zostało zablokowane w przeglądarce"; return "🔕 Powiadomienia wyłączone"; }
function decode(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const base64 = (value + padding).replace(/-/g, "+").replace(/_/g, "/"); return Uint8Array.from(atob(base64), character => character.charCodeAt(0)); }
