"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ALERT_PREFERENCES_STORAGE_KEY, parseAlertPreferences } from "../preferences";
import { DEFAULT_ALERT_PREFERENCES, type AlertPreferences } from "../types";

export function AlertSettings(){
  const[settings,setSettings]=useState<AlertPreferences>(()=>{if(typeof window==="undefined")return DEFAULT_ALERT_PREFERENCES;try{return parseAlertPreferences(JSON.parse(localStorage.getItem(ALERT_PREFERENCES_STORAGE_KEY)??"null"));}catch{return DEFAULT_ALERT_PREFERENCES;}}); const[saved,setSaved]=useState(false);
  const update=<K extends keyof AlertPreferences>(key:K,value:AlertPreferences[K])=>{setSettings(current=>({...current,[key]:value}));setSaved(false)}; const save=()=>{localStorage.setItem(ALERT_PREFERENCES_STORAGE_KEY,JSON.stringify(settings));setSaved(true)};
  return <section className="ui-section"><div><h2 className="font-heading text-xl font-bold">Ustawienia alertów</h2><p className="mt-1 text-sm text-muted-foreground">Filtry alertów i powiadomień dla tego urządzenia.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberSetting label="Minimalny Flip Score" value={settings.minFlipScore} onChange={value=>update("minFlipScore",value??85)}/><NumberSetting label="Minimalny Opportunity Score" value={settings.minOpportunityScore} onChange={value=>update("minOpportunityScore",value??85)}/><NumberSetting label="Maksymalna cena" value={settings.maxPrice} onChange={value=>update("maxPrice",value)}/><NumberSetting label="Maksymalna cena/m²" value={settings.maxPricePerSqm} onChange={value=>update("maxPricePerSqm",value)}/><Toggle label="Tylko prywatni sprzedający" checked={settings.privateOnly} onChange={value=>update("privateOnly",value)}/><Toggle label="Tylko Facebook" checked={settings.facebookOnly} onChange={value=>update("facebookOnly",value)}/><Toggle label="Tylko Łódź" checked={settings.lodzOnly} onChange={value=>update("lodzOnly",value)}/><Toggle label="Tylko mieszkania do remontu" checked={settings.renovationOnly} onChange={value=>update("renovationOnly",value)}/><Toggle label="Powiadamiaj o obniżkach cen" checked={settings.priceDrops} onChange={value=>update("priceDrops",value)}/><label className="grid gap-1 text-sm sm:col-span-2">Wybrane osiedla<input className="h-11 rounded-xl border bg-background px-3" placeholder="Teofilów, Radogoszcz, Retkinia, Widzew" value={settings.neighborhoods.join(", ")} onChange={event=>update("neighborhoods",event.target.value.split(",").map(value=>value.trim()).filter(Boolean))}/></label></div><div className="mt-5 flex items-center gap-3"><Button onClick={save}>Zapisz ustawienia</Button>{saved?<span className="text-sm text-success">Zapisano na tym urządzeniu.</span>:null}</div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["E-mail","Telegram"].map(channel=><div className="rounded-xl border border-dashed p-4" key={channel}><p className="font-semibold">{channel}</p><p className="mt-1 text-xs text-muted-foreground">Adapter przygotowany · kanał wyłączony</p></div>)}</div></section>;
}
function NumberSetting({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){return <label className="grid gap-1 text-sm">{label}<input className="h-11 rounded-xl border bg-background px-3" min="0" type="number" value={value??""} onChange={event=>onChange(event.target.value?Number(event.target.value):null)}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex min-h-11 items-center gap-3 rounded-xl border px-3 text-sm"><input checked={checked} className="size-4 accent-current" type="checkbox" onChange={event=>onChange(event.target.checked)}/>{label}</label>}
